---
title: "Projekt"
author: "Stefan Graf"
date: "28 3 2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Loading environment / libraries

# Todo:

# Data handling
# Zeiten kontrollieren ob bei Originaldatei in den Tracks (anhand Dateiname) teilweise GPS Messungen mit viel späterem Zeitpunkt zwischendrin vorkommen


```{r import, echo= 'F',results='hide'}
# CLASSICAL PACKAGE IMPORTER (Stefan Graf & Tobias Frey)
packages_checker <- function(packages_list){
  for (package in packages_list){
    if (!require(package, character.only = T)) {
      install.packages(package)
    }
    library(package, character.only = T)
  }
}

packages_checker(
  c('lubridate'
    ,'zoo',
    'dbplyr',
    'plyr',
    'dplyr',
    'tidyr',
    'tidyverse',
    'sf', # Simple feature --> super spatial data handling structure
    'raster', # For raster data
    'ggspatial',
    'rgdal',
    'data.table',
    'RColorBrewer', # color schemas from color brewer web
    'ggraph', # visualization
    'igraph',
    'tmap',
    'scales',
    'trajr',
    'plotly', # zoomable, pannable ggplot
    'mapview',
    'ggmap', # easier interactive ggmaps 
    'leaflet', # Javascript library (originally) for plotting on a maptile interactive map
    'tmap',
    'stringr',
    'remotes' # geom_convexhull function
    ))
rm(list = ls())
getwd()

### CUSTOM FUNCTIONS ###
clockS = function(t){hour(t)*3600+minute(t)*60+second(t)}
```

#### SUAQ research site
## Data manipulation /exploration / wrangling

```{r SUAQ}
#### SUAQ TRACKS ####
# Function to read files with filename as column --> in our case alter filename specifc for these datasets using regex
read_plus <- function(flnm) {
    read_csv(flnm,skip = 22) %>%  # Skip the first 16 rows because see below
        mutate(filename = flnm) 
}
suaq_csv_list<- list.files(path = "./data/2019_SUAQ/",pattern = "*.csv",full.names = T)

# Basecamp GDB to CSV writes the metadate in the first 16 columns. Then the wayspoints and after that the device tracking points. So we have to split the file afterwards again.
SUAQ_data<- list.files(path = "./data/2019_SUAQ/",pattern = "*.csv",full.names = T) %>% 
  map_df(~read_plus(.))

# Get the metainfo from the filename
## Todo: REGEX parsing (Date: "\d{4}.\d{3}" Fileninfos: "\d{8}_[a-zA-Z].+_\w\w")

# 1st get rid of full path
SUAQ_data<- SUAQ_data %>% mutate(fileN=substr(str_extract(filename, "\\d{8}_[a-zA-Z].+_.+\\."), 1, nchar(str_extract(filename, "\\d{8}_[a-zA-Z].+_.+\\."))-4))

# 2nd extract the 5 attributes ,filedate, orangutanname, infant name, followername, followtype
SUAQ_data <-
  SUAQ_data %>% mutate(
    filedate = str_extract(fileN, "\\d{8}"),
    orangutanname = substr(
      str_extract(fileN, "\\d{8}_[A-Z][a-z]+"),
      10,
      nchar(str_extract(fileN, "\\d{8}_[A-Z][a-z]+"))
    ),
    infantname = substr(
      str_extract(fileN, "_[A-Z][a-z]+(\\([A-Z][a-z]+\\)|[A-Z][a-z]+)"),
      2 + nchar(orangutanname),
      nchar(
        str_extract(fileN, "_[A-Z][a-z]+(\\([A-Z][a-z]+\\)|[A-Z][a-z]+)")
      )
    ),
    followername = substr(
      str_extract(fileN, "_[A-Z][a-z_]+_[A-Z]{2}"),
      2,
      nchar(str_extract(fileN, "_[A-Z][a-z_]+_[A-Z]{2}")) - 3
    ),
    followtype = substr(
      str_extract(fileN, "_[A-Z][a-z_]+_[A-Z]{2}"),
      nchar(str_extract(fileN, "_[A-Z][a-z_]+_[A-Z]{2}")) - 1,
      nchar(str_extract(fileN, "_[A-Z][a-z_]+_[A-Z]{2}"))
    )
  )
SUAQ_data <- SUAQ_data[,colSums(is.na(SUAQ_data))<nrow(SUAQ_data)]

levels(as.factor(SUAQ_data$orangutanname)) # testing some levels of created columns
levels(as.factor(SUAQ_data$fileN))[1]

tmp <- subset(SUAQ_data,SUAQ_data$fileN==levels(as.factor(SUAQ_data$fileN))[1])
if (levels(as.factor(SUAQ_data$fileN))[1]==levels(as.factor(SUAQ_data$fileN))[1]){
    waypoints<- tmp %>% slice(1:(which(grepl('trksegID', tmp$lat))-14))
    trackpoints <- tmp %>% slice(which(grepl('trksegID', tmp$lat))+1:n())
    colnames(trackpoints) <-tmp %>%filter(.$lat=='trksegID')
}else{
  
}

tmp <- subset(SUAQ_data,SUAQ_data$fileN==levels(as.factor(SUAQ_data$fileN))[1])

levels(as.factor(SUAQ_data$fileN))[87]
which(grepl('Address', tmp$lat))
# Create file with waypoints and file with trackpoints (device)
for (n in 1:length(levels(as.factor(SUAQ_data$fileN)))){
  print(n)
  #Subset the data by MP
  tmp <- subset(SUAQ_data,SUAQ_data$fileN==levels(as.factor(SUAQ_data$fileN))[n])
  if (n==1){
    waypoints<- tmp %>% slice(1:(which(grepl('Address', tmp$lat))-1))
    trackpoints <- tmp %>% slice(which(grepl('trksegID', tmp$lat))+1:n())
    colnames(trackpoints) <-tmp %>%filter(.$lat=='trksegID')
  }
  else{
    waypoints_tmp<- tmp %>% slice(1:(which(grepl('Address', tmp$lat))-1))
    print('Trackpoints')
    trackpoints_tmp<-tmp<-tmp %>% slice(which(grepl('trksegID', tmp$lat))+1:n())
    print("hello")
    colnames(trackpoints_tmp) <-colnames(trackpoints)
    
    waypoints<- rbind(waypoints,waypoints_tmp)
    trackpoints <- rbind(trackpoints,trackpoints_tmp)
  }
}

# CRS Code: EPSG 32647
# Create SF Points
suaq_orangutan_waypoints <- waypoints %>% drop_na(lat,lon)
suaq_orangutan_follows_sf <-  st_as_sf(suaq_orangutan_waypoints, 
                          coords = c("lat", "lon"), 
                          crs = 4326)

coordinates_tmp <- st_coordinates(suaq_orangutan_follows_sf)
colnames(coordinates_tmp) <- c("E","N")
suaq_orangutan_follows_sf <- cbind(suaq_orangutan_follows_sf,coordinates_tmp)

##### DATA WRANGLING ######
# Create timelag
suaq_orangutan_follows_sf<- suaq_orangutan_follows_sf %>% 
  group_by(fileN)%>% 
  mutate(timelag=as.numeric(difftime(lead(as.POSIXlt(CreationTime)),as.POSIXlt(CreationTime),units = "secs"))) # change datetime to time, see analysis below

suaq_neg_timelag <- suaq_orangutan_follows_sf %>% filter(timelag<0)

##### Set a GPS Tracking Laufnummer oder Lösung des Zeitproblems ##### 
# Begründung: In den Tracks kommen teilweise Punkte vor welche zu einer viel späteren Zeit gemacht wurden. Oder wurde Zeit falsch gespeichert (bzw. lief umwandlung in Indonesische Zeitzone falsch)
#suaq_orangutan_follows_sf<- suaq_orangutan_follows_sf %>%  arrange(desc(datetime))

#SUAQ_data<- SUAQ_data %>%  arrange(desc(.$CreationTime))

# Laufnummer für GPS Punkt erstellen




## Create DateTime from time column (time is not datetime)
suaq_orangutan_follows_sf <- suaq_orangutan_follows_sf %>%
  mutate(datetime=with_tz(ymd_hms(CreationTime),"Asia/Pontianak"))
suaq_orangutan_follows_sf <- suaq_orangutan_follows_sf %>%
  mutate(date=date(datetime), truetime=hms::as_hms(datetime))

suaq_orangutan_follows_sf %>% ggplot(aes(truetime))+geom_histogram()
suaq_orangutan_follows_sf %>% ggplot(aes(hms::as_hms(CreationTime)))+geom_histogram() # time before conversion

follows_points_in_night<- suaq_orangutan_follows_sf %>% filter(truetime<lubridate::hms("04:00:00")) # probably one outlier and one track in the night. Or wrong time settings

```
## Calculate timelag 
- Corrected time --> datetime, 
```{r Timelag suaq}
# Timelag histogram
summary(suaq_orangutan_follows_sf$timelag)
suaq_orangutan_follows_sf %>% ggplot(aes(suaq_orangutan_follows_sf$timelag))+
  geom_histogram(binwidth = )
suaq_orangutan_follows_sf <- suaq_orangutan_follows_sf %>% filter(timelag<0)

# dates have the same distribution
ketambe_orangutan_tracks_sf %>% ggplot(aes(date_tmp))+geom_histogram()
ketambe_orangutan_tracks_sf %>% ggplot(aes(dateandtime))+geom_histogram()

# change the calculation of timelag to time_tmp
```

### Analysis
## First visuals SUAQ
```{r Visualization Suaq}
##### VISUALIZE ######
# Grouping and visualize it
plot1<- suaq_orangutan_follows_sf %>% 
  group_by(fileN) %>%
  ggplot(aes(E,N))+
  geom_point(aes(color=suaq_orangutan_follows_sf$orangutanname),size=0.3)+
  geom_path(aes(color=suaq_orangutan_follows_sf$orangutanname), alpha = 0.2,size=0.3)

# Grouping --> research tracklengths / number of points per track / time intervall tracks
suaq_num_point_follows<- suaq_orangutan_follows_sf %>% 
  group_by(fileN) %>%
  tally()

suaq_num_point_follows_histogram<- suaq_num_point_follows %>% ggplot(aes(n))+
  geom_histogram()+
  xlab("Lenght of follow [num of waypoints]")+
  ylab("num of waypoints")
suaq_num_point_follows_histogram

# Zoom-Panable map of tracks
ggplotly(plot1)

# plot specific track
pal<- brewer.pal(30, "BrBG")

plot_tmp<- suaq_orangutan_follows_sf %>% 
  filter(fileN=='20190113_Lisa(Leon)_Saidi_NN.') %>%
  ggplot(aes(E,N, label=paste(ID,time)))+
  geom_point()+
  geom_path()+
  geom_text(aes(label=paste(ID,truetime)),position = position_nudge(y = -0.0003),size=3)
ggplotly(plot_tmp)


plot_tmp<- suaq_orangutan_follows_sf %>% 
  filter(fileN=='20190113_Lisa(Leon)_Saidi_NN.') %>% 
  arrange(desc(datetime)) %>% 
  ggplot(aes(E,N, label=paste(ID,time)))+
  geom_point()+
  geom_path()+
  geom_text(aes(label=paste(ID,truetime)),position = position_nudge(y = -0.0003),size=3)
ggplotly(plot_tmp)


# Map with tiles (leaflet)



# create convex hulls on points of each orangutan
suaq_orangutan_chulls_2019 <- suaq_orangutan_follows_sf %>%
  group_by(orangutanname) %>% 
  summarise(geometry = st_combine(geometry) ) %>%
  st_convex_hull()

plot_tmp<- ggplot(suaq_orangutan_chulls_2019) + geom_sf(data = suaq_orangutan_chulls_2019, aes(colour = orangutanname,alpha=1),fill=NA)
ggplotly(plot_tmp)

## next idea homerange per month or year (need more years!)

# suaq_orangutan_chulls_month <- suaq_orangutan_follows_sf %>%
#   group_by(orangutanname) %>%
#   summarise(geometry = st_combine(geometry)) %>%
#   st_convex_hull()
# rownames(suaq_orangutan_chulls_month) <- suaq_orangutan_chulls_month$orangutanname
# 
# suaq_orangutan_chulls_january <- suaq_orangutan_follows_sf %>%
#   filter(between(datetime, as.Date("2019-01-01"),as.Date("2019-01-31"))) %>% 
#   group_by(orangutanname) %>%
#   summarise(geometry = st_combine(geometry)) %>%
#   st_convex_hull()
# colnames(suaq_orangutan_chulls_january)[2]
# class(suaq_orangutan_chulls_january$geometry[1])
# 
# suaq_orangutan_chulls_month<-bind_cols(suaq_orangutan_chulls_month, suaq_orangutan_chulls_january,by = c("orangutanname" = "orangutanname"))
# ?full_join
# 
# suaq_orangutan_chulls %>% ggplot()+
#     geom_polygon(suaq_orangutan_chulls$geometry)
# plot_tmp<- ggplot(suaq_orangutan_chulls) + geom_sf(data = suaq_orangutan_chulls, aes(colour = orangutanname,alpha=1),fill=NA)
# ggplotly(plot_tmp)




```
