---
title: "SUAQr_homeranges"
author: "Stefan Graf"
date: "2/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Markings:
#### Quality check: --> are quality checks of chunks executed before
########### DELETE ############--> are chunks to delete
## Title --> are titles for sections
### explanations of the following chunk
##### SUAQ TRACKS 2018 & 2019 ##### --> Code sections to understand code better

```{r import, echo= 'F',results='hide'}
# CLASSICAL PACKAGE IMPORTER (Stefan Graf & Tobias Frey)
packages_checker <- function(packages_list){
  for (package in packages_list){
    if (!require(package, character.only = T)) {
      install.packages(package)
    }
    library(package, character.only = T)
  }
}

packages_checker(
  c('tlocoh',
    'tmap',
    'tmaptools',# read_gpx function
    'hrbrthemes', # for colors --> viridis
    'rgdal',
    'ctmm',
    'lubridate',
    'plyr',
    'dplyr',
    'tidyr',
    'tidyverse',
    'sf', # Simple feature --> super spatial data handling structure
    'raster', # For raster data
    'rgdal',
    'plotly', # zoomable, pannable ggplot
    'move',# Brownian Bridge Movement Model
    'adehabitatHR',
    'lme4',
    'nlme',
    'ggplot2',
    'ggpubr',
    'GGally',
    'ggfortify', #check linear regression assumptions
    'GGally', # usefull pairs function to create many scatterplots
    'maptools',# used in move package
    'viridis',
    'lmerTest',
    'sp',
    'ks' # used in KDE functions
    ))
#install.packages("tlocoh", dependencies=TRUE, repos=c("http://R-Forge.R-project.org", "http://cran.cnr.berkeley.edu"), type="source")
#require(tlocoh)

rm(list = ls())
getwd()



### CUSTOM FUNCTIONS ###

# Function for displaying scale labels in ggplot not as f.e. 4e+05
fancy_scientific <- function(l) {
     # turn in to character string in scientific notation
     l <- format(l, scientific = TRUE)
     # quote the part before the exponent to keep all the digits
     l <- gsub("^(.*)e", "'\\1'e", l)
     # turn the 'e+' into plotmath format
     l <- gsub("e", "%*%10^", l)
     # return this as an expression
     parse(text=l)
}


clockS = function(t){hour(t)*3600+minute(t)*60+second(t)}
st_kde <- function(points,cellsize, bandwith, extent = NULL){
  require(MASS)
  require(raster)
  require(sf)
  if(is.null(extent)){
    extent_vec <- st_bbox(points)[c(1,3,2,4)]
  } else{
    extent_vec <- st_bbox(extent)[c(1,3,2,4)]
  }
  
  n_y <- ceiling((extent_vec[4]-extent_vec[3])/cellsize)
  n_x <- ceiling((extent_vec[2]-extent_vec[1])/cellsize)
  
  extent_vec[2] <- extent_vec[1]+(n_x*cellsize)-cellsize
  extent_vec[4] <- extent_vec[3]+(n_y*cellsize)-cellsize
  
  coords <- st_coordinates(points)
  matrix <- kde2d(coords[,1],coords[,2],h = bandwith,n = c(n_x,n_y),lims = extent_vec)
  raster(matrix)
}




#### Custom functions for analysis
clockS = function(t){hour(t)*3600+minute(t)*60+second(t)}


euclid <- function(x1,y1,x2,y2){
  return(sqrt((x1-x2)^2+(y1-y2)^2))
}

turning_angle <- function(x,y,lead_lag = 1){ 
  if(length(x) < 3){return(NA)}
  if(length(x) != length(y)){stop("x and y must be of the same length")}
  p1x <- lag(x,lead_lag)
  p1y <- lag(y,lead_lag)
  p2x <- x
  p2y <- y
  p3x <- lead(x,lead_lag)
  p3y <- lead(y,lead_lag)
  p12 <- euclid(p1x,p1y,p2x,p2y)
  p13 <- euclid(p1x,p1y,p3x,p3y)
  p23 <- euclid(p2x,p2y,p3x,p3y)
  rad <- acos((p12^2+p23^2-p13^2)/(2*p12*p23))
  grad <- (rad*180)/pi
  grad[p12 == 0 | p23 == 0] <- NA
  d <-  (p3x-p1x)*(p2y-p1y)-(p3y-p1y)*(p2x-p1x)
  d <- ifelse(d == 0,1,d)
  d[d>0] <- 1
  d[d<0] <- -1
  d[d==0] <- 1
  turning <- grad*d*-1+180
  return(turning)
}

# Source https://exploratory.io/note/kanaugust/1701090969905358
calculate_mode <- function(x) {
  uniqx <- unique(na.omit(x))
  uniqx[which.max(tabulate(match(x, uniqx)))]
}


# Statistics from here: https://github.com/aufrank/R-hacks/blob/master/mer-utils.R
vif.mer <- function (fit) {
    ## adapted from rms::vif

    v <- vcov(fit)
    nam <- names(fixef(fit))

    ## exclude intercepts
    ns <- sum(1 * (nam == "Intercept" | nam == "(Intercept)"))
    if (ns > 0) {
        v <- v[-(1:ns), -(1:ns), drop = FALSE]
        nam <- nam[-(1:ns)]
    }

    d <- diag(v)^0.5
    v <- diag(solve(v/(d %o% d)))
    names(v) <- nam
    v
}




setwd("/Users/stefgr/Nextcloud/UZH/12_Semester/20200313_Masterthesis/R/")

```

#### SUAQ homerange analysis

```{r GPS Loader,echo=FALSE, message=FALSE,comment=FALSE, warning=FALSE}
### Load Project variables ### 
##### waypoints ##### "data/Processed_data/SUAQ_waypoints_11all20.csv"
##### ATTENTION: read_csv guesses a columns type as boolean if first 1200 entries are NA
# find most recent file
mostrecent <- list.files(path = "data/Processed_data/", full.names = FALSE, recursive = FALSE)
mostrecent <- as.data.frame(mostrecent)
mostrecent <- mostrecent %>% filter(grepl("SUAQ_waypoints_11all20",mostrecent)) %>% 
  mutate(date=as.numeric(str_extract(mostrecent,"\\d{8}"))) %>% arrange(desc(date)) %>% top_n(1,date)

SUAQ_waypoints_11all20_loc <-
  read_csv(paste0("data/Processed_data/",mostrecent$date[1],"_SUAQ_waypoints_11all20.csv"),guess_max = min(10000, 30000))
SUAQ_waypoints_11all20_loc <- SUAQ_waypoints_11all20_loc %>% mutate(monthYearDate=format(as.Date(manualDate), "%Y-%m"))
SUAQ_waypoints_11all20_loc <- SUAQ_waypoints_11all20_loc %>% mutate(automaticDatetime=with_tz(automaticDatetime,tz = "Asia/Pontianak"))
SUAQ_waypoints_11all20_loc <- SUAQ_waypoints_11all20_loc %>% mutate(manualDatetime=with_tz(manualDatetime,tz = "Asia/Pontianak"))



#### add party individuals as individual gps points.
SUAQ_waypoints_11all20_loc_party <- SUAQ_waypoints_11all20_loc %>% filter(PtType%in%c("party"))

SUAQ_waypoints_11all20_loc_party1 <- SUAQ_waypoints_11all20_loc_party %>% 
  dplyr::select(altitude,name_original,sym,fileN,gpsextraction,gpsextractionquality,filedate,followername,manualDatetime, manualTime, manualDate, automaticDatetime, automaticTime,automaticDate,PtType,E,N,AgeSex,follow,PtType_individual_1) %>% filter(!is.na(PtType_individual_1)) %>%  mutate(focal=PtType_individual_1) %>% dplyr::select(-PtType_individual_1) 

SUAQ_waypoints_11all20_loc_party2 <- SUAQ_waypoints_11all20_loc_party %>% 
  dplyr::select(altitude,name_original,sym,fileN,gpsextraction,gpsextractionquality,filedate,followername,manualDatetime, manualTime, manualDate, automaticDatetime, automaticTime,automaticDate,PtType,E,N,AgeSex,follow,PtType_individual_2) %>% filter(!is.na(PtType_individual_2)) %>%  mutate(focal=PtType_individual_2) %>% dplyr::select(-PtType_individual_2) 

#### Combine datasets if for one follow there is an individual at party1 and at party2 position (f.e. if maybe at the first party point another individual was present but at the second on the same follow not) its still gets one new follownumber.
SUAQ_waypoints_11all20_loc_party <- SUAQ_waypoints_11all20_loc_party1 %>% bind_rows(SUAQ_waypoints_11all20_loc_party2)

SUAQ_waypoints_11all20_loc_party <- SUAQ_waypoints_11all20_loc_party%>% 
  group_by(fileN,focal,manualDate,follow) %>% # if .$follow it can be modified later idk why with only "follow" it doesnt work
  mutate(follow = as.numeric(cur_group_id()+1110000)) ## adding FN above 11

SUAQ_waypoints_11all20_loc <- SUAQ_waypoints_11all20_loc %>% 
  bind_rows(SUAQ_waypoints_11all20_loc_party)

##### Weather and FAI #####
SUAQ_weather <- read_csv("data/Processed_data/SUAQ_weather.csv")
SUAQ_fai <- read_csv("data/Processed_data/SUAQ_fai.csv")

SUAQ_weather_monthly<-SUAQ_weather %>% 
  group_by(SUAQ_weather.year,SUAQ_weather.month) %>% 
  summarise_all(funs(mean))
SUAQ_weather_monthly<- SUAQ_weather_monthly%>% dplyr::select(-SUAQ_weather.weather_id,-SUAQ_weather.day,-SUAQ_weather.daymonthyear)

##### location network ##### 
SUAQ_locationnetwork_sf <- st_read("data/20201201_StudyBalimbingStudyArea_points.GPX")
SUAQ_locationnetwork_sf_loc <- st_transform(SUAQ_locationnetwork_sf,crs = 23847)
##### for locale coordinate system
coordinates_tmp <- st_coordinates(SUAQ_locationnetwork_sf_loc)
colnames(coordinates_tmp) <- c("E","N")
SUAQ_locationnetwork_sf_loc <- cbind(SUAQ_locationnetwork_sf_loc,coordinates_tmp)
SUAQ_locationnetwork_loc <- st_drop_geometry(SUAQ_locationnetwork_sf_loc)

SUAQ_pathnetwork<- as.data.frame(read_GPX(file="data/SUAQ_Peta_WithLines.GPX",layers = c("routes")))
colnames(SUAQ_pathnetwork)[15]<- "geometry"
SUAQ_pathnetwork_sf<- st_as_sf(SUAQ_pathnetwork,crs=4326)
SUAQ_pathnetwork_sf_loc <- st_transform(SUAQ_pathnetwork_sf,crs = 23847)

##### physical features for plots
SUAQ_river_sf_wgs<- st_read(dsn="data/external/GeodataIndonesia/Wasser/fluss_50k_perimetergross.shp")
SUAQ_river_sf_loc <- st_transform(SUAQ_river_sf_wgs,crs = 23847)

SUAQ_smallriver_sf_wgs<- st_read(dsn="data/external/GeodataIndonesia/Wasser/kleinflüsse_50k_perimetergross.shp")
SUAQ_smallriver_sf_loc <- st_transform(SUAQ_smallriver_sf_wgs,crs = 23847)

SUAQ_contour_sf_wgs<- st_read(dsn="data/external/GeodataIndonesia/Hoehenllinien/hohenlinien_50k_perimetergross.shp")
SUAQ_contour_sf_loc <- st_transform(SUAQ_contour_sf_wgs,crs = 23847)

SUAQ_station_sf_wgs<- st_read(dsn="data/external/researchstation.shp")
SUAQ_station_sf_loc <- st_transform(SUAQ_station_sf_wgs,crs = 23847)

##### Selection only pointtypes which are taken on the orangutan way? is this true for all? ##### 
SUAQ_rangepoints_11all20_loc <- SUAQ_waypoints_11all20_loc %>% filter(PtType %in% c("daynest","found","lost","mornnest","nightnest","range","tree")) # get rid of lcg lch points and

##### Recalculate edge lengths etc. based on new point selection for rangepoints dataframe
SUAQ_rangepoints_11all20_loc<- SUAQ_rangepoints_11all20_loc %>% 
  group_by(follow)%>% arrange(manualTime,.by_group = TRUE) %>% 
  mutate(timelag=as.numeric(difftime(as.POSIXlt(manualTime),
                                     as.POSIXlt(lag(manualTime)),units 
                                     ="secs")),
         # calculate distance with approach number 1 --> st_distance but to do that we need to calculate lead first because the lead function doesnt work within st distance (not same datatype (df))
         timelag_lead=as.numeric(difftime(as.POSIXlt(lead(manualTime)),
                                          as.POSIXlt(manualTime),units ="secs")),
         manual_distTolast=sqrt((E-lag(E))^2+(N-lag(N))^2),
         manual_distToNext=sqrt((E-lead(E))^2+(N-lead(N))^2),
         speed_last = manual_distTolast/timelag,
         speed_next = manual_distToNext/timelag_lead,
         turningAngle=turning_angle(E,N),
         altitudediff_next=altitude-lead(altitude),
         )





##### WGS84 file
SUAQ_rangepoints_11all20_loc_sf <-  st_as_sf(SUAQ_rangepoints_11all20_loc, 
                          coords = c("E","N"), 
                          crs = 23847) # can also do that in the new sricpts
SUAQ_rangepoints_11all20_loc_wgs <- st_transform(SUAQ_rangepoints_11all20_loc_sf,4326)
coordinates_tmp <- st_coordinates(SUAQ_rangepoints_11all20_loc_wgs)
colnames(coordinates_tmp) <- c("long","lat")
SUAQ_rangepoints_11all20_loc_wgs <- cbind(SUAQ_rangepoints_11all20_loc_wgs,coordinates_tmp)
SUAQ_rangepoints_11all20_loc_wgs<- st_drop_geometry(SUAQ_rangepoints_11all20_loc_wgs)


##### Selection only females / most tracked females ##### 
SUAQ_rangepoints_11all20_loc_females <-
  SUAQ_rangepoints_11all20_loc %>%   filter(!(SUAQ_orangutans.Sex == "male")) %>% ungroup()

SUAQ_rangepoints_11all20_loc_above50GPS <- SUAQ_rangepoints_11all20_loc %>% filter(orangutan_tot_num_of_gps>250) %>% 
  filter(!(ClassFocal%in%c("character(0)","infant","juvenile")))
levels(as.factor(SUAQ_rangepoints_11all20_loc$ClassFocal))
SUAQ_rangepoints_11all20_loc_females_above50GPS <- SUAQ_rangepoints_11all20_loc %>% filter(!(SUAQ_orangutans.Sex == "male")) %>% filter(orangutan_tot_num_of_gps>50)

SUAQ_rangepoints_11all20_loc_males_above50GPS <- SUAQ_rangepoints_11all20_loc %>% filter((SUAQ_orangutans.Sex == "male")) %>% filter(orangutan_tot_num_of_gps>50)

SUAQ_rangepoints_11all20_loc_females_10 <-
  SUAQ_rangepoints_11all20_loc %>%   filter(!(SUAQ_orangutans.Sex == "male")) %>% filter(
    focal %in% c(
      "lisa",
      "friska",
      "ellie",
      "cissy",
      "lilly",
      "yulia",
      "raffi",
      "sarabi",
      "trident",
      "tiara"
    )
  )%>% ungroup()

#### Read in most recent bandwiths for KDE if not newly calculated
mostrecent <- list.files("/Users/stefgr/Nextcloud/UZH/12_Semester/20200313_Masterthesis/R/output/Homeranges/KDE/bandwiths/", full.names = FALSE, recursive = FALSE)
mostrecent <- as.data.frame(mostrecent)
colnames(mostrecent) <- c("date")
mostrecent <- mostrecent %>% filter(date!="_archive") %>%  arrange(desc(date)) %>% top_n(1,date)
imdir <-paste("/Users/stefgr/Nextcloud/UZH/12_Semester/20200313_Masterthesis/R/output/Homeranges/KDE/bandwiths/")
bandwiths <- read_csv(paste0(imdir,paste(mostrecent$date[1], sep="")))

#### Homerange calculations parameter
### Extent
# use always same extent
extentmargin <- 500
axisshifty <- 125 # shift of axis in plots y axis
axisshiftx <- -280 # shift of axis in plots x axis
legendoffsetx <- 0
legendoffsety <- 0
xmin <- min(SUAQ_rangepoints_11all20_loc_females_10$E)-extentmargin; xmax <- max(SUAQ_rangepoints_11all20_loc_females_10$E)+extentmargin
ymin <- min(SUAQ_rangepoints_11all20_loc_females_10$N)-extentmargin; ymax <- max(SUAQ_rangepoints_11all20_loc_females_10$N)+extentmargin
step <- 200
xmin_xmax_round_steps<- c(step*(ceiling(xmin/step)):(round(xmax/step)))
xmin_xmax_round_steps <- xmin_xmax_round_steps[2:(length(xmin_xmax_round_steps)-2)] #manual adjustment of tick breaks how many does it need
ymin_ymax_round_steps<- c(step*(ceiling(ymin/step)):(round(ymax/step)))
ymin_ymax_round_steps <- ymin_ymax_round_steps[2:(length(ymin_ymax_round_steps)-1)] #manual adjustment of tick breaks how many does it need

#### research periods data as list
# Split the data into 4 sampling periods. Calculate the respective HR.
SUAQ_rangepoints_11all20_loc_females_10 <- SUAQ_rangepoints_11all20_loc_females_10 %>% mutate(year=year(manualDatetime))

# make 5 lists for all 4 research periods and one for all data
mt_list <- split(SUAQ_rangepoints_11all20_loc_females_10, f = SUAQ_rangepoints_11all20_loc_females_10$researchperiod)

# add all data as the 5th list (period)
mt_list[["total research period"]] <- SUAQ_rangepoints_11all20_loc_females_10
mt_list <- mt_list[c("total research period","before 2012","2012 until 2016","2016 until August 2018","Since August 2018")]

#### Selected animals as list/vector
selected_females <- SUAQ_rangepoints_11all20_loc_females_10 %>% group_by(focal) %>% summarise()
selected_females <- as_vector(selected_females)


```

Homerange sizes:

```{r CTMM - HR size online,echo=FALSE, message=FALSE,comment=FALSE, warning=FALSE}

##### Save Dataset for CTMM online f.e.
SUAQ_rangepoints_11all20_loc_females12_wgs <- SUAQ_rangepoints_11all20_loc_wgs[order(SUAQ_rangepoints_11all20_loc_wgs$focal,SUAQ_rangepoints_11all20_loc_wgs$manualDatetime , decreasing = TRUE ),] %>% rename(
    c("event-id"="identification","timestamp"="manualDatetime","location-long"="long","location-lat"="lat","Animal ID"="focal","Tag No"="follow")
  ) %>% filter(`Animal ID`%in% c("lisa","friska","ellie","cissy","lilly","yulia","raffi","sarabi","trident","alice","tiara","cinnamon")) %>% mutate("sensor-type"="gps")
write_csv(SUAQ_rangepoints_11all20_loc_wgs, path = paste(
  paste(
    "/Users/stefgr/Nextcloud/UZH/12_Semester/20200313_Masterthesis/R/data/Processed_data/",
    "SUAQ_rangepoints_11all20_loc_females12_wgs",
    sep = ""
  ),
  "csv",
  sep = "."
))
SUAQ_rangepoints_11all20_loc_females6_wgs <- SUAQ_rangepoints_11all20_loc_wgs[order(SUAQ_rangepoints_11all20_loc_wgs$focal,SUAQ_rangepoints_11all20_loc_wgs$manualDatetime , decreasing = TRUE ),] %>% rename(
    c("event-id"="identification","timestamp"="manualDatetime","location-long"="long","location-lat"="lat","Animal ID"="focal","Tag No"="follow")
  ) %>% filter(`Animal ID`%in% c("lisa","friska","ellie","cissy","lilly","yulia")) %>% mutate("sensor-type"="gps")
write_csv(SUAQ_rangepoints_11all20_loc_females6_wgs, path = paste(
  paste(
    "/Users/stefgr/Nextcloud/UZH/12_Semester/20200313_Masterthesis/R/data/Processed_data/",
    "SUAQ_rangepoints_11all20_loc_females6_wgs",
    sep = ""
  ),
  "csv",
  sep = "."
))



```

### Analysis
```{r MCP - HR per-researchperiods and all ,echo=FALSE, message=FALSE,comment=FALSE, warning=FALSE}
# createa directory for kde periods calculation (named by the current date)
dir.create(paste(
    "output/Homeranges/MCP/periods/",
    format(Sys.Date(), "%Y%m%d"),
    sep = ""
  ))
imdir <- paste("output/Homeranges/MCP/periods/",format(Sys.Date(), "%Y%m%d"), "/", sep="")


mcp_list <- data.frame()

for (samplinginterval in c(1:length(mt_list))){
  print(paste("mcp for period: ",samplinginterval))
  ##### Determine the smoothing parameters
  selected_females <- mt_list[[samplinginterval]] %>% group_by(focal) %>% summarise()
  selected_females <- as_vector(selected_females)
  
  iterator <- 1
  for (i in selected_females) { # do the following for every animal in the list
    print(paste("mcp for focal: ",i))
    n_follows <- mt_list[[samplinginterval]] %>% filter(focal%in%c(i)) %>%
        group_by(follow) %>% summarise() %>% nrow() # just as a variable for later results dataframe --> number of follows

    xy_selected <- mt_list[[samplinginterval]] %>% filter(focal%in%c(i)) %>%
      dplyr::select(E,N)
    n_gps <- xy_selected %>% nrow() # just as a variable for later results dataframe --> number of GPS points
    
    coordinates(xy_selected) <- c("E","N")
    proj4string(xy_selected) <- CRS( "+proj=utm +zone=47 +a=6378160 +b=6356774.50408554 +towgs84=-24,-15,5,0,0,0,0 +units=m +no_defs" )
    
    # check if enough gps points are still here otherwise make NA's
    xy_selected_toolessdata <- TRUE
    if(length(xy_selected)<30){xy_selected_toolessdata <- FALSE}
    
    iterator <- iterator+1
    
      if(xy_selected_toolessdata){# only execute when enough data
      hr100<- mcp(xy_selected,percent = 100)
      hr99 <- mcp(xy_selected,percent = 99)
      hr95 <- mcp(xy_selected,percent = 95)
      hr50 <- mcp(xy_selected,percent = 50)
      hr100_area <- mcp.area(xy_selected, percent = 100)
      hr99_area <- mcp.area(xy_selected, percent = 99)
      hr95_area <- mcp.area(xy_selected, percent = 95)
      hr50_area <- mcp.area(xy_selected, percent = 50)
      hr100_sf<- st_as_sf(hr100)
      hr99_sf<- st_as_sf(hr99)
      hr95_sf<- st_as_sf(hr95)
      hr50_sf<- st_as_sf(hr50)
      
      png(paste(imdir,i, "_MCP_UD_",names(mt_list)[samplinginterval], ".png", sep=""), width=900, height=700, res=120, units="px")
      plot(xy_selected,pch = 16,cex=0.3,fill="darkolivegreen", xlab="x [m]",ylab="y [m]",xlim=c(xmin_xmax_round_steps[1],tail(xmin_xmax_round_steps,n=1)),ylim=c(ymin_ymax_round_steps[1],tail(ymin_ymax_round_steps,n=1)))
      plot(hr50, lty=3, lwd=2.5, border="coral1", add=T,axes=F)
      plot(hr95, lty=1, lwd=2, border="cadetblue2", add=T, axes=F)
      plot(hr99, lty=4, lwd=0.8, border="darkturquoise", add=T, axes=F)
      plot(SUAQ_contour_sf_loc,lty=3, lwd=0.2, col=alpha("black", 1), add=T, axes=F)
      plot(SUAQ_station_sf_loc,pch = 21,cex=1.5, col=alpha("black", 0.7), add=T, axes=F)
      plot(SUAQ_station_sf_loc,pch = 16,cex=1, col=alpha("darkred", 0.7),lwd=0.3, bg="darkred", add=T, axes=F)
      plot(SUAQ_river_sf_loc,lty=1, lwd=0.3, col=alpha("cornflowerblue", 0.7), add=T, axes=F)
      plot(SUAQ_pathnetwork_sf_loc, lty=1, lwd=0.3, col=alpha("darkred", 0.7), add=T, axes=F)
      axis(1, at=xmin_xmax_round_steps,pos=ymin+axisshifty) # x axis
      axis(2, at=ymin_ymax_round_steps, pos=xmin+axisshiftx)
      title(paste(i, " : ",names(mt_list)[samplinginterval], sep=""), line=-1.5)
      legend("topright", c("HR 50%", "HR 95%", "HR 100%","Trail","River"), col=c("coral1", "cadetblue2", "darkturquoise","darkred",alpha("cornflowerblue", 0.7)), lwd=c(2.5,2,2,0.3,4), lty=c(3,1,4,1,1), inset=c(legendoffsety,legendoffsety))
      dev.off()
      }
      

    ########## export results ############
    if (xy_selected_toolessdata) {
      resultList_50 <-
        data.frame(
          focal = i,
          homerange = hr50_area$a,
          hrpercentage = "50%",
          n_gps = n_gps,
          n_follows = n_follows,
          period = names(mt_list)[samplinginterval],
          geometry= hr50_sf$geometry
        )
      resultList_95 <-
        data.frame(
          focal = i,
          homerange = hr95_area$a,
          hrpercentage = "95%",
          n_gps = n_gps,
          n_follows = n_follows,
          period = names(mt_list)[samplinginterval],
          geometry= hr95_sf$geometry
        )
      resultList_99 <-
        data.frame(
          focal = i,
          homerange = hr99_area$a,
          hrpercentage = "99%",
          n_gps = n_gps,
          n_follows = n_follows,
          period = names(mt_list)[samplinginterval],
          geometry= hr99_sf$geometry
        )
      resultList_100 <-
        data.frame(
          focal = i,
          homerange = hr100_area$a,
          hrpercentage = "100%",
          n_gps = n_gps,
          n_follows = n_follows,
          period = names(mt_list)[samplinginterval],
          geometry= hr100_sf$geometry
        )
    }
    if (!xy_selected_toolessdata) {
      resultList_50 <-
        data.frame(
          focal = i,
          homerange = NA,
          hrpercentage = "50%",
          n_gps = n_gps,
          n_follows = n_follows,
          period = names(mt_list)[samplinginterval],
          geometry= NA
        )
      resultList_95 <-
        data.frame(
          focal = i,
          homerange = NA,
          hrpercentage = "95%",
          n_gps = n_gps,
          n_follows = n_follows,
          period = names(mt_list)[samplinginterval],
          geometry= NA
        )
      resultList_99 <-
        data.frame(
          focal = i,
          homerange = NA,
          hrpercentage = "99%",
          n_gps = n_gps,
          n_follows = n_follows,
          period = names(mt_list)[samplinginterval],
          geometry= NA
        )
      resultList_100 <-
        data.frame(
          focal = i,
          homerange = NA,
          hrpercentage = "100%",
          n_gps = n_gps,
          n_follows = n_follows,
          period = names(mt_list)[samplinginterval],
          geometry= NA
        )
    }
    mcp_list <- mcp_list %>% rbind(resultList_50,resultList_95,resultList_99,resultList_100)
    print(paste(i,": Calculation finished", sep=""))
  }
}

st_write(mcp_list, dsn = paste(
  paste(
    imdir,
    "mcp_values_allperiods",
    sep = ""
  ),
  "shp",
  sep = "."
))
#system("say alle minimum konvex Polygone berechnet für die verschiedenen Untersuchungsperioden")


```

```{r MCP - HR per-year ,echo=FALSE, message=FALSE,comment=FALSE, warning=FALSE}
# createa directory for kde periods calculation (named by the current date)
dir.create(paste(
    "output/Homeranges/MCP/years/",
    format(Sys.Date(), "%Y%m%d"),
    sep = ""
  ))
imdir <- paste("output/Homeranges/MCP/years/",format(Sys.Date(), "%Y%m%d"), "/", sep="")


mcp_list <- data.frame() # results

for (samplinginterval in c(1:length(mt_list))){
  print(paste("mcp for period: ",samplinginterval))
  ##### Determine the smoothing parameters
  selected_females <- mt_list[[samplinginterval]] %>% group_by(focal) %>% summarise()
  selected_females <- as_vector(selected_females)
  
  iterator <- 1
  for (i in selected_females) { # do the following for every animal in the list
    print(paste("mcp for focal: ",i))
    n_follows <- mt_list[[samplinginterval]] %>% filter(focal%in%c(i)) %>%
        group_by(follow) %>% summarise() %>% nrow() # just as a variable for later results dataframe --> number of follows

    xy_selected <- mt_list[[samplinginterval]] %>% filter(focal%in%c(i)) %>%
      dplyr::select(E,N)
    n_gps <- xy_selected %>% nrow() # just as a variable for later results dataframe --> number of GPS points
    
    coordinates(xy_selected) <- c("E","N")
    proj4string(xy_selected) <- CRS( "+proj=utm +zone=47 +a=6378160 +b=6356774.50408554 +towgs84=-24,-15,5,0,0,0,0 +units=m +no_defs" )
    
    # check if enough gps points are still here otherwise make NA's
    xy_selected_toolessdata <- TRUE
    if(length(xy_selected)<30){xy_selected_toolessdata <- FALSE}
    
    iterator <- iterator+1
    
      if(xy_selected_toolessdata){# only execute when enough data
      hr100<- mcp(xy_selected,percent = 100)
      hr99 <- mcp(xy_selected,percent = 99) 
      hr95 <- mcp(xy_selected,percent = 95)
      hr50 <- mcp(xy_selected,percent = 50)
      hr100_area <- mcp.area(xy_selected, percent = 100)
      hr99_area <- mcp.area(xy_selected, percent = 99)
      hr95_area <- mcp.area(xy_selected, percent = 95)
      hr50_area <- mcp.area(xy_selected, percent = 50)
  
      
      png(paste(imdir,i, "_MCP_UD_",names(mt_list)[samplinginterval], ".png", sep=""), width=900, height=700, res=120, units="px")
      plot(xy_selected,pch = 16,cex=0.3,fill="darkolivegreen", xlab="x [m]",ylab="y [m]",xlim=c(xmin_xmax_round_steps[1],tail(xmin_xmax_round_steps,n=1)),ylim=c(ymin_ymax_round_steps[1],tail(ymin_ymax_round_steps,n=1)))
      plot(hr50, lty=3, lwd=2.5, border="coral1", add=T,axes=F)
      plot(hr95, lty=1, lwd=2, border="cadetblue2", add=T, axes=F)
      plot(hr99, lty=4, lwd=2, border="darkturquoise", add=T, axes=F)
      plot(SUAQ_contour_sf_loc,lty=3, lwd=0.2, col=alpha("black", 1), add=T, axes=F)
      plot(SUAQ_station_sf_loc,pch = 21,cex=1.5, col=alpha("black", 0.7), add=T, axes=F)
      plot(SUAQ_station_sf_loc,pch = 16,cex=1, col=alpha("darkred", 0.7),lwd=0.3, bg="darkred", add=T, axes=F)
      plot(SUAQ_river_sf_loc,lty=1, lwd=0.3, col=alpha("cornflowerblue", 0.7), add=T, axes=F)
      plot(SUAQ_pathnetwork_sf_loc, lty=1, lwd=0.3, col=alpha("darkolivegreen", 0.7), add=T, axes=F)
      axis(1, at=xmin_xmax_round_steps,pos=ymin+axisshifty) # x axis
      axis(2, at=ymin_ymax_round_steps, pos=xmin+axisshiftx)
      title(paste(i, " : ",names(mt_list)[samplinginterval], sep=""), line=-1.5)
      legend("topright", c("HR 50%", "HR 95%", "HR 100%","Trail","River"), col=c("coral1", "cadetblue2", "darkturquoise","darkred",alpha("cornflowerblue", 0.7)), lwd=c(2.5,2,2,0.3,4), lty=c(3,1,4,1,1), inset=c(legendoffsety,legendoffsety))
      dev.off()
      }
      

    ########## export results ############
    if (xy_selected_toolessdata) {
      resultList_50 <-
        data.frame(
          focal = i,
          homerange = hr50_area$a,
          hrpercentage = "50%",
          n_gps = n_gps,
          n_follows = n_follows,
          period = names(mt_list)[samplinginterval],
          geometry= hr50_sf$geometry
        )
      resultList_95 <-
        data.frame(
          focal = i,
          homerange = hr95_area$a,
          hrpercentage = "95%",
          n_gps = n_gps,
          n_follows = n_follows,
          period = names(mt_list)[samplinginterval],
          geometry= hr95_sf$geometry
        )
      resultList_99 <-
        data.frame(
          focal = i,
          homerange = hr99_area$a,
          hrpercentage = "99%",
          n_gps = n_gps,
          n_follows = n_follows,
          period = names(mt_list)[samplinginterval],
          geometry= hr99_sf$geometry
        )
      resultList_100 <-
        data.frame(
          focal = i,
          homerange = hr100_area$a,
          hrpercentage = "100%",
          n_gps = n_gps,
          n_follows = n_follows,
          period = names(mt_list)[samplinginterval],
          geometry= hr100_sf$geometry
        )
    }
    if (!xy_selected_toolessdata) {
      resultList_50 <-
        data.frame(
          focal = i,
          homerange = NA,
          hrpercentage = "50%",
          n_gps = n_gps,
          n_follows = n_follows,
          period = names(mt_list)[samplinginterval],
          geometry= NA
        )
      resultList_95 <-
        data.frame(
          focal = i,
          homerange = NA,
          hrpercentage = "95%",
          n_gps = n_gps,
          n_follows = n_follows,
          period = names(mt_list)[samplinginterval],
          geometry= NA
        )
      resultList_99 <-
        data.frame(
          focal = i,
          homerange = NA,
          hrpercentage = "99%",
          n_gps = n_gps,
          n_follows = n_follows,
          period = names(mt_list)[samplinginterval],
          geometry= NA
        )
      resultList_100 <-
        data.frame(
          focal = i,
          homerange = NA,
          hrpercentage = "100%",
          n_gps = n_gps,
          n_follows = n_follows,
          period = names(mt_list)[samplinginterval],
          geometry= NA
        )
    }
    mcp_list <- mcp_list %>% rbind(resultList_50,resultList_95,resultList_99,resultList_100)
    print(paste(i,": Calculation finished", sep=""))
  }
}

st_write(mcp_list, dsn = paste(
  paste(
    imdir,
    "mcp_values_years",
    sep = ""
  ),
  "shp",
  sep = "."
))
system("say alle minimum konvex Polygone berechnet für jedes Jahr")


```

```{r MCP -  HR sizes with bootstrap ,echo=FALSE, message=FALSE,comment=FALSE, warning=FALSE}


### Homerange Stability
##### Using MCP --> The latter plot probably shows more the usage then the stability because mcp.area takes the points away based on their spatial location
mcp.area(SUAQ_rangepoints_11all20_loc_females_more50GPS.sp, percent = seq(30, 90, by = 5))

##### FEMALES: Using MCP bootstrapping, randomly selecting points
SUAQ_move_selected <- SUAQ_rangepoints_11all20_loc_females_above50GPS[order(SUAQ_rangepoints_11all20_loc_females_above50GPS$focal,SUAQ_rangepoints_11all20_loc_females_above50GPS$manualDatetime , decreasing = FALSE ),] %>% ungroup()

SUAQ_move_selected <- move(x=SUAQ_move_selected$E, y=SUAQ_move_selected$N, 
              time=as.POSIXct(SUAQ_move_selected$manualDatetime, format="%Y-%m-%d %H:%M:%OS", tz="Asia/Pontianak"),
              proj=CRS("+proj=utm +zone=47 +a=6378160 +b=6356774.50408554 +towgs84=-24,-15,5,0,0,0,0 +units=m +no_defs"), 
              data=SUAQ_move_selected, animal=SUAQ_move_selected$focal, sensor="gps")
hrBootstrap(x=SUAQ_move_selected, rep=25,level=100,
            levelMax=100, unin="m",unout='km2')

##### Exkurs MALES: Using MCP bootstrapping, randomly selecting points
SUAQ_move_selected <- SUAQ_rangepoints_11all20_loc_above50GPS[order(SUAQ_rangepoints_11all20_loc_above50GPS$focal,SUAQ_rangepoints_11all20_loc_above50GPS$manualDatetime , decreasing = FALSE ),] %>% ungroup()

SUAQ_move_selected <- move(x=SUAQ_move_selected$E, y=SUAQ_move_selected$N, 
              time=as.POSIXct(SUAQ_move_selected$manualDatetime, format="%Y-%m-%d %H:%M:%OS", tz="Asia/Pontianak"),
              proj=CRS("+proj=utm +zone=47 +a=6378160 +b=6356774.50408554 +towgs84=-24,-15,5,0,0,0,0 +units=m +no_defs"), 
              data=SUAQ_move_selected, animal=SUAQ_move_selected$focal, sensor="gps")
all<- hrBootstrap(x=SUAQ_move_selected, rep=25,level=100,plot=FALSE,
            levelMax=100, unin="m",unout='km2')
all_flatten<- data.frame(do.call(rbind, all))
all_flatten$name<- rownames(all_flatten)
all_flatten <- all_flatten %>% rowwise() %>%  mutate(focal=strsplit(name,"\\.")[[1]][1],points=as.numeric(strsplit(name,"\\.")[[1]][2])) %>% 
  dplyr::select(-name) %>% left_join(SUAQ_orangutans[,c(1,3)],by=c("focal"="orangutanname")) 

all_flatten %>% ggplot()+geom_path(aes(x=points,X50.,colour=focal,linetype=Sex)) + scale_x_log10()+
  geom_path(aes(x=points,X50.,colour=focal,linetype=Sex))+
  geom_path(aes(x=points,X0.,colour=focal,linetype=Sex,alpha=0.5))+
  geom_path(aes(x=points,X100.,colour=focal,linetype=Sex,alpha=0.5))
```

```{r KDE - parametrization,echo=FALSE, message=FALSE,comment=FALSE, warning=FALSE}
##### Determine the smoothing parameters
bandwiths <-  data.frame(focal=as_vector(selected_females),
                 hpi=vector(mode="numeric", length=10),hbcv=vector(mode="numeric", length=10),hscv=vector(mode="numeric", length=10),
                 stringsAsFactors=FALSE)
iterator <- 1
for (i in selected_females){
  print(paste("calculating bandwiths for focal: ",i))
  xy_selected <- SUAQ_rangepoints_11all20_loc_females_10 %>% filter(focal%in%c(i)) %>% dplyr::select(E,N)
  colnames(xy_selected) <- c("x","y") #adjust column names
  hpi <- sqrt(prod(sqrt(diag(Hpi.diag(xy_selected[,1:2], nstage=2))))) # using diagonal bandwith not full bandwith? why?
  hbcv <- sqrt(prod(sqrt(diag(Hbcv.diag(xy_selected[,1:2], whichbcv=1)))))
  hscv <- sqrt(prod(sqrt(diag(Hscv.diag(xy_selected[,1:2], nstage=2)))))
  bandwiths[iterator,"focal"] <- i
  bandwiths[iterator,"hpi"] <- as.numeric(hpi)
  bandwiths[iterator,"hbcv"] <- as.numeric(hbcv)
  bandwiths[iterator,"hscv"] <- as.numeric(hscv)

  iterator <- iterator+1
}
rownames(bandwiths) <- c(1:10)

write_csv(bandwiths, path = paste(
  paste(
    "/Users/stefgr/Nextcloud/UZH/12_Semester/20200313_Masterthesis/R/output/Homeranges/KDE/bandwiths/",
    format(Sys.Date(), "%Y%m%d"),
    "_KDE_bandwiths",
    sep = ""
  ),
  "csv",
  sep = "."
))
```

```{r KDE - HR sizes with bootstrap,echo=FALSE, message=FALSE,comment=FALSE, warning=FALSE}
#bandwiths <- read_csv(paste0("data/Processed_data/",str_remove_all(Sys.Date(), "-"),"_KDE_bandwiths.csv"))

dir.create(paste(
    "output/Homeranges/KDE/",
    format(Sys.Date(), "%Y%m%d"),
    sep = ""
  ))

# iterator
iterator <- 1
for (i in selected_females){ # compute KDE home range for every individual
  xy_selected <- SUAQ_rangepoints_11all20_loc_females_10 %>% filter(focal%in%c(i)) %>% dplyr::select(E,N)
  colnames(xy_selected) <- c("x","y") #adjust column names
  resultList <- list()
  methListTitle <- list("REF", "PI", "BCV", "SCV")
  methList <- list("HREF", "HPI", "HBCV", "HSCV")
  
  xy_selected <- SpatialPoints(xy_selected,proj4string = CRS( "+proj=utm +zone=47 +a=6378160 +b=6356774.50408554 +towgs84=-24,-15,5,0,0,0,0 +units=m +no_defs" )) # Converts SpatialPointDataFrame to SpatialPoint (only x & y)
  
  extVal <- 0.3 #0.3 How much bigger the UD should be calculated than the research are (minimum bounding box). The higher the more Computation
  gridVal <- 800 #700 How much cells or pixels should be considered for UD calculation. The higher the more Computation
  
  for (j in seq(1, length(methList))) { # compute one home range for each bandwidth method and individual
    if (j == 1) {
      UD <- (kernelUD(xy_selected, grid=gridVal, extent=extVal, h="href"))
    }
    else if (j == 2) {
      UD <- (kernelUD(xy_selected, grid=gridVal, extent=extVal, h=bandwiths[iterator,"hpi"]))
    }
    else if (j == 3) {
      UD <- (kernelUD(xy_selected, grid=gridVal, extent=extVal, h=bandwiths[iterator,"hbcv"]))
    }
    else if (j == 4) {
      UD <- (kernelUD(xy_selected, grid=gridVal, extent=extVal, h=bandwiths[iterator,"hscv"])) 
    }
    else {
      print("Error")
    }
    
    hr95 <- getverticeshr(UD, percent=95,unin = c("m"),unout = c("km2"))
    hr50 <- getverticeshr(UD, percent=50,unin = c("m"),unout = c("km2"))
    
    ########## plot results ##########
    imdir <- paste("output/Homeranges/KDE/",format(Sys.Date(), "%Y%m%d"), "/", sep="")
    imdirUD <- paste("output/Homeranges/KDE/",format(Sys.Date(), "%Y%m%d"),"/", sep="")
    step <- 200
    xmin_xmax_round_steps<- c(step*(ceiling(xmin/step)):(round(xmax/step)))
    xmin_xmax_round_steps <- xmin_xmax_round_steps[2:(length(xmin_xmax_round_steps)-2)] #manual adjustment of tick breaks how many does it need
    ymin_ymax_round_steps<- c(step*(ceiling(ymin/step)):(round(ymax/step)))
    ymin_ymax_round_steps <- ymin_ymax_round_steps[2:(length(ymin_ymax_round_steps)-1)] #manual adjustment of tick breaks how many does it need

    par(mar=c(1,1,1,1))
    
    png(paste(imdirUD, selected_females[[iterator]], "_KDE_UD_", methList[[j]], ".png", sep=""), width=900, height=700, res=120, units="px")
    image(UD, xlab="x [m]",xlim=c(xmin_xmax_round_steps[1],tail(xmin_xmax_round_steps,n=1)),ylim=c(ymin_ymax_round_steps[1],tail(ymin_ymax_round_steps,n=1))) 
    plot(hr50, lty=4, lwd=1, border="azure4", add=T,axes=F)
    plot(hr95, lty=1, lwd=0.6, border="cadetblue2", add=T, axes=F)
    axis(1, at=xmin_xmax_round_steps,pos =ymin+axisshifty )
    axis(2, at=ymin_ymax_round_steps, pos=xmin+axisshiftx)
    text(xmin-100, (ymin+ymax)/2, "y [m]", adj=c(NA,-4), srt=90)
    title(paste(selected_females[[iterator]], ": KDE ", "(", methListTitle[[j]], ")", sep=""), line=-0.3)
    legend("topright", c("HR 50%", "HR 95%"), col=c("black", "blue"), lwd=c(1,0.6), lty=c(4,1), inset=c(0.17,0.11))
    dev.off()

    png(paste(imdir, selected_females[[iterator]], "_KDE_VUD_", methList[[j]], ".png", sep=""), width=900, height=700, res=120, units="px")
    image(getvolumeUD(UD), xlab="x [m]",xlim=c(xmin_xmax_round_steps[1],tail(xmin_xmax_round_steps,n=1)),ylim=c(ymin_ymax_round_steps[1],tail(ymin_ymax_round_steps,n=1)))
    plot(hr50, lty=4, lwd=1, border="azure4", add=T,axes=F)
    plot(hr95, lty=1, lwd=0.6, border="cadetblue2", add=T, axes=F)
    axis(1, at=xmin_xmax_round_steps,pos =ymin+axisshifty )
    axis(2, at=ymin_ymax_round_steps, pos=xmin+axisshiftx)
    text(xmin-100, (ymin+ymax)/2, "y [m]", adj=c(NA,-4), srt=90)
    title(paste(selected_females[[iterator]], ": KDE ", "(", methListTitle[[j]], ")", sep=""), line=-0.3)
    legend("topright", c("HR 50%", "HR 95%"), col=c("black", "blue"), lwd=c(1,0.6), lty=c(4,1), inset=c(0.17,0.11))
    dev.off()
    
    ########## export results #########
    resultList <- list(hr50=hr50, hr95=hr95, UD=UD)
    assign(methList[[j]], resultList) #resultList is renamed according to the ith element of methList
  }
  animRes <- list(HREF=HREF, HPI=HPI, HBCV=HBCV, HSCV=HSCV)
  assign(selected_females[[iterator]], animRes) # is renamed according to the ith element of animList
  print(paste(selected_females[[iterator]], ": Calculation finished", sep=""))
  
  iterator <- iterator+1
}
kde <- data.frame(focal=as_vector(selected_females),
                 HREF_hr50area=vector(mode="numeric", length=10),
                 HREF_hr95area=vector(mode="numeric", length=10),
                 HPI_hr50area=vector(mode="numeric", length=10),
                 HPI_hr95area=vector(mode="numeric", length=10),
                 HBCV_hr50area=vector(mode="numeric", length=10),
                 HBCV_hr95area=vector(mode="numeric", length=10),
                 HSCV_hr50area=vector(mode="numeric", length=10),
                 HSCV_hr95area=vector(mode="numeric", length=10),
                 stringsAsFactors=FALSE)
kde_list <- list(lisa=lisa,
      friska=friska,
      ellie=ellie,
      cissy=cissy,
      lilly=lilly,
      yulia=yulia,
      raffi=raffi,
      sarabi=sarabi,
      trident=trident,
      tiara=tiara)
iterator <- 1
for(i in as_vector(selected_females)){
  kde[iterator,"HREF_hr50area"] <-  kde_list[[i]]$HREF$hr50$area
  kde[iterator,"HREF_hr95area"] <- kde_list[[i]]$HREF$hr95$area
  kde[iterator,"HPI_hr50area"] <-kde_list[[i]]$HPI$hr50$area
  kde[iterator,"HPI_hr95area"] <- kde_list[[i]]$HPI$hr95$area
  kde[iterator,"HBCV_hr50area"] <-  kde_list[[i]]$HBCV$hr50$area
  kde[iterator,"HBCV_hr95area"] <-  kde_list[[i]]$HBCV$hr95$area
  kde[iterator,"HSCV_hr50area"] <-  kde_list[[i]]$HSCV$hr50$area
  kde[iterator,"HSCV_hr95area"] <-  kde_list[[i]]$HSCV$hr95$area
  iterator <- iterator+1
}
rownames(kde) <- c(1:10)

### KDE-stability:
for(iter in c(2:30)){
amountofdata <- seq(0.5,10,by=0.5)/10
kde95_bootstrap <- data.frame(focal=as_vector(selected_females),
                 HSCV_area_5=vector(mode="numeric", length=10),             
                 HSCV_area_10=vector(mode="numeric", length=10),
                 HSCV_area_15=vector(mode="numeric", length=10),
                 HSCV_area_20=vector(mode="numeric", length=10),
                 HSCV_area_25=vector(mode="numeric", length=10),
                 HSCV_area_30=vector(mode="numeric", length=10),
                 HSCV_area_35=vector(mode="numeric", length=10),
                 HSCV_area_40=vector(mode="numeric", length=10),
                 HSCV_area_45=vector(mode="numeric", length=10),
                 HSCV_area_50=vector(mode="numeric", length=10),
                 HSCV_area_55=vector(mode="numeric", length=10),
                 HSCV_area_60=vector(mode="numeric", length=10),
                 HSCV_area_65=vector(mode="numeric", length=10),
                 HSCV_area_70=vector(mode="numeric", length=10),
                 HSCV_area_75=vector(mode="numeric", length=10),
                 HSCV_area_80=vector(mode="numeric", length=10),
                 HSCV_area_85=vector(mode="numeric", length=10),
                 HSCV_area_90=vector(mode="numeric", length=10),
                 HSCV_area_95=vector(mode="numeric", length=10),
                 HSCV_area_100=vector(mode="numeric", length=10),
                 stringsAsFactors=FALSE)
kde50_bootstrap <- data.frame(focal=as_vector(selected_females),
                 HSCV_area_5=vector(mode="numeric", length=10),             
                 HSCV_area_10=vector(mode="numeric", length=10),
                 HSCV_area_15=vector(mode="numeric", length=10),
                 HSCV_area_20=vector(mode="numeric", length=10),
                 HSCV_area_25=vector(mode="numeric", length=10),
                 HSCV_area_30=vector(mode="numeric", length=10),
                 HSCV_area_35=vector(mode="numeric", length=10),
                 HSCV_area_40=vector(mode="numeric", length=10),
                 HSCV_area_45=vector(mode="numeric", length=10),
                 HSCV_area_50=vector(mode="numeric", length=10),
                 HSCV_area_55=vector(mode="numeric", length=10),
                 HSCV_area_60=vector(mode="numeric", length=10),
                 HSCV_area_65=vector(mode="numeric", length=10),
                 HSCV_area_70=vector(mode="numeric", length=10),
                 HSCV_area_75=vector(mode="numeric", length=10),
                 HSCV_area_80=vector(mode="numeric", length=10),
                 HSCV_area_85=vector(mode="numeric", length=10),
                 HSCV_area_90=vector(mode="numeric", length=10),
                 HSCV_area_95=vector(mode="numeric", length=10),
                 HSCV_area_100=vector(mode="numeric", length=10),
                 stringsAsFactors=FALSE)


for(per in amountofdata){
  iterator <- 1
for (i in selected_females){ # compute KDE home range for every individual
  xy_selected <- SUAQ_rangepoints_11all20_loc_females_10 %>% filter(focal%in%c(i)) %>% dplyr::select(E,N)
  xy_selected<- sample_n(xy_selected, round(nrow(xy_selected)*per))

  colnames(xy_selected) <- c("x","y") #adjust column names
  xy_selected <- SpatialPoints(xy_selected,proj4string = CRS( "+proj=utm +zone=47 +a=6378160 +b=6356774.50408554 +towgs84=-24,-15,5,0,0,0,0 +units=m +no_defs" )) # Converts SpatialPointDataFrame to SpatialPoint (only x & y)

  
  resultList <- list()
  methListTitle <- list("SCV")
  methList <- list("HSCV")
  
  
  extVal <- 0.4 #0.3 How much bigger the UD should be calculated than the research are (minimum bounding box). The higher the more Computation
  gridVal <- 800 #700 How much cells or pixels should be considered for UD calculation. The higher the more Computation
  
  for (j in seq(1, length(methList))) { # compute one home range for each bandwidth method and individual
    if (j == 1) {
      UD <- (kernelUD(xy_selected, grid=gridVal, extent=extVal, h=bandwiths[iterator,"hscv"])) 
    }
    else {
      print("Error")
    }
    
    hr95 <- getverticeshr(UD, percent=95,unin = c("m"),unout = c("km2"))
    hr50 <- getverticeshr(UD, percent=50,unin = c("m"),unout = c("km2"))
    
    ########## export results #########
    resultList <- list(hr50=hr50, hr95=hr95, UD=UD)
    assign(methList[[j]], resultList) #resultList is renamed according to the ith element of methList
  }
  animRes <- list(HSCV=HSCV)
  assign(selected_females[[iterator]], animRes) # is renamed according to the ith element of animList
  print(paste(selected_females[[iterator]], ": Calculation finished with Subset of ",as.character(100*per),"% of Points", sep=""))
  
  iterator <- iterator+1
}
  kde_list <- list(lisa=lisa,
      friska=friska,
      ellie=ellie,
      cissy=cissy,
      lilly=lilly,
      yulia=yulia,
      raffi=raffi,
      sarabi=sarabi,
      trident=trident,
      tiara=tiara)
  itera <- 1
for(n in as_vector(selected_females)){
  kde50_bootstrap[itera,paste("HSCV_area","_",as.character(100*per),sep = "")] <-  kde_list[[n]]$HSCV$hr50$area
  kde95_bootstrap[itera,paste("HSCV_area","_",as.character(100*per),sep = "")] <-  kde_list[[n]]$HSCV$hr95$area
  itera <- itera+1
}
}
colnames(kde95_bootstrap) <- c("focal",as.character(seq(0.5,10,0.5)*10))
kde95_bootstrap_long_iter<- gather(kde95_bootstrap,as.character(seq(0.5,10,0.5)*10),key="subset %",value = "HR [km2]")
kde95_bootstrap_long_iter <- kde95_bootstrap_long_iter %>% mutate(`subset %`=as.numeric(`subset %`))
kde95_bootstrap_long_iter <- kde95_bootstrap_long_iter %>% mutate(iteration=iter)
kde95_bootstrap_long <- kde95_bootstrap_long %>% rbind(kde95_bootstrap_long_iter)

colnames(kde50_bootstrap) <- c("focal",as.character(seq(0.5,10,0.5)*10))
kde50_bootstrap_long_iter<- gather(kde50_bootstrap,as.character(seq(0.5,10,0.5)*10),key="subset %",value = "HR [km2]")
kde50_bootstrap_long_iter <- kde50_bootstrap_long_iter %>% mutate(`subset %`=as.numeric(`subset %`))
kde50_bootstrap_long_iter <- kde50_bootstrap_long_iter %>% mutate(iteration=iter)
kde50_bootstrap_long <- kde50_bootstrap_long %>% rbind(kde50_bootstrap_long_iter)
}




colnames(kde95_bootstrap) <- c("focal",as.character(seq(0.5,10,0.5)*10))
kde95_bootstrap_long<- gather(kde95_bootstrap,as.character(seq(0.5,10,0.5)*10),key="subset %",value = "HR [km2]")
kde95_bootstrap_long <- kde95_bootstrap_long %>% mutate(`subset %`=as.numeric(`subset %`))
kde95_bootstrap_long <- kde95_bootstrap_long %>% mutate(iteration=1)

colnames(kde50_bootstrap) <- c("focal",as.character(seq(0.5,10,0.5)*10))
kde50_bootstrap_long<- gather(kde50_bootstrap,as.character(seq(0.5,10,0.5)*10),key="subset %",value = "HR [km2]")
kde50_bootstrap_long <- kde50_bootstrap_long %>% mutate(`subset %`=as.numeric(`subset %`))
kde50_bootstrap_long <- kde50_bootstrap_long %>% mutate(iteration=1)



kde50_bootstrap_long %>%  ggplot(aes(`subset %`,`HR [km2]`,colour=focal)) + geom_line()
rownames(kde) <- c(1:10)
kde95_bootstrap_long %>%  ggplot(aes(`subset %`,`HR [km2]`,colour=focal)) + geom_point(size=0.3)+geom_jitter(size=0.3)
rownames(kde) <- c(1:10)
```

```{r KDE - HR per-researchperiods and all - HR sizes,echo=FALSE, message=FALSE,comment=FALSE, warning=FALSE}
# createa directory for kde periods calculation (named by the current date)
dir.create(paste(
    "output/Homeranges/KDE/periods/",
    format(Sys.Date(), "%Y%m%d"),
    sep = ""
  ))
imdir <- paste("output/Homeranges/KDE/periods/",format(Sys.Date(), "%Y%m%d"), "/", sep="")

kde_results_perperiod <- data.frame() # results
for (samplinginterval in c(1:length(mt_list))){
print(paste("kdes for period: ",samplinginterval))
##### Determine the smoothing parameters
selected_females <- mt_list[[samplinginterval]] %>% group_by(focal) %>% summarise()
selected_females <- as_vector(selected_females)

bandwiths <-  data.frame(focal=as_vector(selected_females),
                 hpi=vector(mode="numeric", length=length(selected_females)),hbcv=vector(mode="numeric", length=length(selected_females)),hscv=vector(mode="numeric", length=length(selected_females)),
                 stringsAsFactors=FALSE)
iterator <- 1
for (i in selected_females){
  print(paste("kdes for focal: ",i))
  xy_selected <- SUAQ_rangepoints_11all20_loc_females_10 %>% filter(focal%in%c(i)) %>% dplyr::select(E,N)
  colnames(xy_selected) <- c("x","y") #adjust column names
  hpi <- sqrt(prod(sqrt(diag(Hpi.diag(xy_selected[,1:2], nstage=2))))) # using diagonal bandwith not full bandwith? why?
  hbcv <- sqrt(prod(sqrt(diag(Hbcv.diag(xy_selected[,1:2], whichbcv=1)))))
  hscv <- sqrt(prod(sqrt(diag(Hscv.diag(xy_selected[,1:2], nstage=2)))))
  bandwiths[iterator,"focal"] <- i
  bandwiths[iterator,"hpi"] <- as.numeric(hpi)
  bandwiths[iterator,"hbcv"] <- as.numeric(hbcv)
  bandwiths[iterator,"hscv"] <- as.numeric(hscv)

  iterator <- iterator+1
}
rownames(bandwiths) <- c(1:length(selected_females))

### KDE: Calculate UD, HR
iterator <- 1
results_focal <- data.frame()
for (i in selected_females){ # compute KDE home range for every individual
  n_follows <- mt_list[[samplinginterval]] %>% filter(focal%in%c(i)) %>% group_by(follow) %>% summarise() %>% nrow()
  xy_selected <- mt_list[[samplinginterval]] %>% filter(focal%in%c(i)) %>% dplyr::select(E,N)
  n_gps <- xy_selected %>% nrow()
  
  colnames(xy_selected) <- c("x","y") #adjust column names
  resultList <- list()
  methListTitle <- list("REF", "PI", "BCV", "SCV")
  methList <- list("HREF", "HPI", "HBCV", "HSCV")
  
  xy_selected <- SpatialPoints(xy_selected,proj4string = CRS( "+proj=utm +zone=47 +a=6378160 +b=6356774.50408554 +towgs84=-24,-15,5,0,0,0,0 +units=m +no_defs" )) # Converts SpatialPointDataFrame to SpatialPoint (only x & y)
  
  extVal <- 15 #0.3 How much bigger the UD should be calculated than the research are (minimum bounding box). The higher the more Computation
  gridVal <- 2000 #700 How much cells or pixels should be considered for UD calculation. The higher the more Computation

  for (j in seq(1, length(methList))) { # compute one home range for each bandwidth method and individual
    if (j == 1) {
      UD <- (kernelUD(xy_selected, grid=gridVal, extent=extVal, h="href"))
    }
    else if (j == 2) {
      UD <- (kernelUD(xy_selected, grid=gridVal, extent=extVal, h=bandwiths[iterator,"hpi"]))
    }
    else if (j == 3) {
      UD <- (kernelUD(xy_selected, grid=gridVal, extent=extVal, h=bandwiths[iterator,"hbcv"]))
    }
    else if (j == 4) {
      UD <- (kernelUD(xy_selected, grid=gridVal, extent=extVal, h=bandwiths[iterator,"hscv"])) 
    }
    else {
      print("Error")
    }
    hr99 <- getverticeshr(UD, percent=99,unin = c("m"),unout = c("km2"))
    hr95 <- getverticeshr(UD, percent=95,unin = c("m"),unout = c("km2"))
    hr50 <- getverticeshr(UD, percent=50,unin = c("m"),unout = c("km2"))
    
    hr99_sf <- st_as_sf(hr99)
    hr95_sf <- st_as_sf(hr95)
    hr50_sf <- st_as_sf(hr50)
    
    ########## plot results ##########
    png(paste(imdir, selected_females[[iterator]],"_",gsub(" ", "", names(mt_list)[samplinginterval], fixed = TRUE), "_KDE_UD_", methList[[j]], ".png", sep=""), width=1800, height=1400, res=240, units="px")
    par(0,0,0,0)
    image(UD, xlab="x [m]",ylab="y [m]",xlim=c(xmin_xmax_round_steps[1],tail(xmin_xmax_round_steps,n=1)),ylim=c(ymin_ymax_round_steps[1],tail(ymin_ymax_round_steps,n=1))) 
    plot(hr50, lty=3, lwd=1.5, border="darkseagreen3", add=T,axes=F)
    plot(hr95, lty=1, lwd=1, border="cadetblue2", add=T, axes=F)
    plot(hr99, lty=4, lwd=1, border="darkturquoise", add=T, axes=F)
    plot(SUAQ_contour_sf_loc,lty=3, lwd=0.2, col=alpha("black", 1), add=T, axes=F)
    plot(SUAQ_station_sf_loc,pch = 21,cex=1.5, col=alpha("black", 0.7), add=T, axes=F)
    plot(SUAQ_station_sf_loc,pch = 16,cex=1, col=alpha("darkred", 0.7),lwd=0.3, bg="darkred", add=T, axes=F)
    plot(SUAQ_river_sf_loc,lty=1, lwd=0.3, col=alpha("cornflowerblue", 0.7), add=T, axes=F)
    plot(SUAQ_pathnetwork_sf_loc, lty=1, lwd=0.3, col=alpha("darkolivegreen", 0.7), add=T, axes=F)
    axis(1, at=xmin_xmax_round_steps,pos=ymin+axisshifty) # x axis
    axis(2, at=ymin_ymax_round_steps, pos=xmin+axisshiftx)
    #text(xmin-550, (ymin+ymax)/2, "y [m]", adj=c(NA,-4), srt=90)
    title(paste(selected_females[[iterator]], ": KDE ", "(", methListTitle[[j]], ")", sep=""), line=-1.5)
    legend("topright", c("HR 50%", "HR 95%", "HR 100%","Trail","River"), col=c("coral1", "cadetblue2", "darkturquoise","darkred",alpha("cornflowerblue", 0.7)), lwd=c(2.5,2,2,0.3,4), lty=c(3,1,4,1,1), inset=c(legendoffsety,legendoffsety))
    dev.off()

    png(paste(imdir, selected_females[[iterator]],"_",gsub(" ", "", names(mt_list)[samplinginterval], fixed = TRUE), "_KDE_VUD_", methList[[j]], ".png", sep=""), width=1800, height=1400, res=240, units="px")
    image(getvolumeUD(UD), xlab="x [m]",ylab="y [m]",xlim=c(xmin_xmax_round_steps[1],tail(xmin_xmax_round_steps,n=1)),ylim=c(ymin_ymax_round_steps[1],tail(ymin_ymax_round_steps,n=1)))
    plot(hr50, lty=3, lwd=1.5, border="azure4", add=T,axes=F)
    plot(hr95, lty=1, lwd=1, border="cadetblue2", add=T, axes=F)
    plot(hr99, lty=4, lwd=1, border="darkturquoise", add=T, axes=F)
    plot(SUAQ_contour_sf_loc,lty=3, lwd=0.2, col=alpha("black", 1), add=T, axes=F)
    plot(SUAQ_station_sf_loc,pch = 21,cex=1.5, col=alpha("black", 0.7), add=T, axes=F)
    plot(SUAQ_station_sf_loc,pch = 16,cex=1, col=alpha("darkred", 0.7),lwd=0.3, bg="darkred", add=T, axes=F)
    plot(SUAQ_river_sf_loc,lty=1, lwd=0.3, col=alpha("cornflowerblue", 0.7), add=T, axes=F)
    plot(SUAQ_pathnetwork_sf_loc, lty=1, lwd=0.3, col=alpha("darkolivegreen", 0.7), add=T, axes=F)
    axis(1, at=xmin_xmax_round_steps,pos=ymin+axisshifty) # x axis
    axis(2, at=ymin_ymax_round_steps, pos=xmin+axisshiftx)
    #text(xmin-500, (ymin+ymax)/2, "y [m]", adj=c(NA,-4), srt=90)
    title(paste(selected_females[[iterator]], ": KDE ", "(", methListTitle[[j]], ")", sep=""), line=-1.5)
    legend("topright", c("HR 50%", "HR 95%", "HR 100%","Trail","River"), col=c("coral1", "cadetblue2", "darkturquoise","darkred",alpha("cornflowerblue", 0.7)), lwd=c(2.5,2,2,0.3,4), lty=c(3,1,4,1,1), inset=c(legendoffsety,legendoffsety))
    dev.off()
    
    results_selectedmethod <- data.frame(bandwithmethod=c(methList[[j]],methList[[j]],methList[[j]]),
            hrpercentage=c("50%","95%","99%"),
            area=c(hr50_sf$area,hr95_sf$area,hr99_sf$area),
            n_gps=c(n_gps,n_gps,n_gps),
            n_follows=c(n_follows,n_follows,n_follows),
            geometry=c(hr50_sf$geometry,hr95_sf$geometry,hr99_sf$geometry))

    results_selectedfocal<- results_selectedmethod %>% mutate(focal=selected_females[[iterator]])
    
    results_focal <- rbind(results_focal,results_selectedfocal)
  }

  

  print(paste(selected_females[[iterator]], ": Calculation finished", sep=""))
  iterator <- iterator+1
}
results_focal <- results_focal %>% mutate(period=names(mt_list)[samplinginterval])
kde_results_perperiod <- kde_results_perperiod %>% rbind(results_focal)


}
st_write(kde_results_perperiod, dsn = paste(
  paste(imdir,
    "kde_values_allperiods",
    sep = ""
  ),
  "shp",
  sep = "."
))
system("say alle kernel distanzen berechnet für die verschiedenen Untersuchungsperioden")


```

```{r KDE - HR per-year - HR sizes,echo=FALSE, message=FALSE,comment=FALSE, warning=FALSE}
# createa directory for kde periods calculation (named by the current date)
dir.create(paste(
    "output/Homeranges/KDE/years/",
    format(Sys.Date(), "%Y%m%d"),
    sep = ""
  ))

kde_results_perperyear <- data.frame() # results
for (samplinginterval in c(1:length(mt_list))){
print(paste("kdes for period: ",samplinginterval))
##### Determine the smoothing parameters
selected_females <- mt_list[[samplinginterval]] %>% group_by(focal) %>% summarise()
selected_females <- as_vector(selected_females)

bandwiths <-  data.frame(focal=as_vector(selected_females),
                 hpi=vector(mode="numeric", length=length(selected_females)),hbcv=vector(mode="numeric", length=length(selected_females)),hscv=vector(mode="numeric", length=length(selected_females)),
                 stringsAsFactors=FALSE)
iterator <- 1
for (i in selected_females){
  print(paste("kdes for focal: ",i))
  xy_selected <- SUAQ_rangepoints_11all20_loc_females_10 %>% filter(focal%in%c(i)) %>% dplyr::select(E,N)
  colnames(xy_selected) <- c("x","y") #adjust column names
  hpi <- sqrt(prod(sqrt(diag(Hpi.diag(xy_selected[,1:2], nstage=2))))) # using diagonal bandwith not full bandwith? why?
  hbcv <- sqrt(prod(sqrt(diag(Hbcv.diag(xy_selected[,1:2], whichbcv=1)))))
  hscv <- sqrt(prod(sqrt(diag(Hscv.diag(xy_selected[,1:2], nstage=2)))))
  bandwiths[iterator,"focal"] <- i
  bandwiths[iterator,"hpi"] <- as.numeric(hpi)
  bandwiths[iterator,"hbcv"] <- as.numeric(hbcv)
  bandwiths[iterator,"hscv"] <- as.numeric(hscv)

  iterator <- iterator+1
}
rownames(bandwiths) <- c(1:length(selected_females))

### KDE: Calculate UD, HR
iterator <- 1
results_focal <- data.frame()
for (i in selected_females){ # compute KDE home range for every individual
  n_follows <- mt_list[[samplinginterval]] %>% filter(focal%in%c(i)) %>% group_by(follow) %>% summarise() %>% nrow()
  xy_selected <- mt_list[[samplinginterval]] %>% filter(focal%in%c(i)) %>% dplyr::select(E,N)
  n_gps <- xy_selected %>% nrow()
  
  colnames(xy_selected) <- c("x","y") #adjust column names
  resultList <- list()
  methListTitle <- list("REF", "PI", "BCV", "SCV")
  methList <- list("HREF", "HPI", "HBCV", "HSCV")
  
  xy_selected <- SpatialPoints(xy_selected,proj4string = CRS( "+proj=utm +zone=47 +a=6378160 +b=6356774.50408554 +towgs84=-24,-15,5,0,0,0,0 +units=m +no_defs" )) # Converts SpatialPointDataFrame to SpatialPoint (only x & y)
  
  extVal <- 15 #0.3 How much bigger the UD should be calculated than the research are (minimum bounding box). The higher the more Computation
  gridVal <- 2000 #700 How much cells or pixels should be considered for UD calculation. The higher the more Computation

  for (j in seq(1, length(methList))) { # compute one home range for each bandwidth method and individual
    if (j == 1) {
      UD <- (kernelUD(xy_selected, grid=gridVal, extent=extVal, h="href"))
    }
    else if (j == 2) {
      UD <- (kernelUD(xy_selected, grid=gridVal, extent=extVal, h=bandwiths[iterator,"hpi"]))
    }
    else if (j == 3) {
      UD <- (kernelUD(xy_selected, grid=gridVal, extent=extVal, h=bandwiths[iterator,"hbcv"]))
    }
    else if (j == 4) {
      UD <- (kernelUD(xy_selected, grid=gridVal, extent=extVal, h=bandwiths[iterator,"hscv"])) 
    }
    else {
      print("Error")
    }
    hr99 <- getverticeshr(UD, percent=99,unin = c("m"),unout = c("km2"))
    hr95 <- getverticeshr(UD, percent=95,unin = c("m"),unout = c("km2"))
    hr50 <- getverticeshr(UD, percent=50,unin = c("m"),unout = c("km2"))
    
    hr99_sf <- st_as_sf(hr99)
    hr95_sf <- st_as_sf(hr95)
    hr50_sf <- st_as_sf(hr50)
    
    ########## plot results ##########
    imdir <- paste("output/Homeranges/KDE/years/",format(Sys.Date(), "%Y%m%d"), "/", sep="")
    imdirUD <- paste("output/Homeranges/KDE/years/",format(Sys.Date(), "%Y%m%d"),"/", sep="")
    step <- 200
    xmin_xmax_round_steps<- c(step*(ceiling(xmin/step)):(round(xmax/step)))
    xmin_xmax_round_steps <- xmin_xmax_round_steps[2:(length(xmin_xmax_round_steps)-2)] #manual adjustment of tick breaks how many does it need
    ymin_ymax_round_steps<- c(step*(ceiling(ymin/step)):(round(ymax/step)))
    ymin_ymax_round_steps <- ymin_ymax_round_steps[2:(length(ymin_ymax_round_steps)-1)] #manual adjustment of tick breaks how many does it need

    png(paste(imdirUD, selected_females[[iterator]],"_",gsub(" ", "", names(mt_list)[samplinginterval], fixed = TRUE), "_KDE_UD_", methList[[j]], ".png", sep=""), width=1800, height=1400, res=240, units="px")
    par(0,0,0,0)
    image(UD, xlab="x [m]",ylab="y [m]",xlim=c(xmin_xmax_round_steps[1],tail(xmin_xmax_round_steps,n=1)),ylim=c(ymin_ymax_round_steps[1],tail(ymin_ymax_round_steps,n=1))) 
    plot(hr50, lty=3, lwd=1.5, border="darkseagreen3", add=T,axes=F)
    plot(hr95, lty=1, lwd=1, border="cadetblue2", add=T, axes=F)
    plot(hr99, lty=4, lwd=1, border="darkturquoise", add=T, axes=F)
    plot(SUAQ_contour_sf_loc,lty=3, lwd=0.2, col=alpha("black", 1), add=T, axes=F)
    plot(SUAQ_station_sf_loc,pch = 21,cex=1.5, col=alpha("black", 0.7), add=T, axes=F)
    plot(SUAQ_station_sf_loc,pch = 16,cex=1, col=alpha("darkred", 0.7),lwd=0.3, bg="darkred", add=T, axes=F)
    plot(SUAQ_river_sf_loc,lty=1, lwd=0.3, col=alpha("cornflowerblue", 0.7), add=T, axes=F)
    plot(SUAQ_pathnetwork_sf_loc, lty=1, lwd=0.3, col=alpha("darkolivegreen", 0.7), add=T, axes=F)
    axis(1, at=xmin_xmax_round_steps,pos=ymin+axisshifty) # x axis
    axis(2, at=ymin_ymax_round_steps, pos=xmin+axisshiftx)
    #text(xmin-550, (ymin+ymax)/2, "y [m]", adj=c(NA,-4), srt=90)
    title(paste(selected_females[[iterator]], ": KDE ", "(", methListTitle[[j]], ")", sep=""), line=-1.5)
    legend("topright", c("HR 50%", "HR 95%", "HR 100%","Trail","River"), col=c("coral1", "cadetblue2", "darkturquoise","darkred",alpha("cornflowerblue", 0.7)), lwd=c(2.5,2,2,0.3,4), lty=c(3,1,4,1,1), inset=c(legendoffsety,legendoffsety))
    dev.off()

    png(paste(imdir, selected_females[[iterator]],"_",gsub(" ", "", names(mt_list)[samplinginterval], fixed = TRUE), "_KDE_VUD_", methList[[j]], ".png", sep=""), width=1800, height=1400, res=240, units="px")
    image(getvolumeUD(UD), xlab="x [m]",ylab="y [m]",xlim=c(xmin_xmax_round_steps[1],tail(xmin_xmax_round_steps,n=1)),ylim=c(ymin_ymax_round_steps[1],tail(ymin_ymax_round_steps,n=1)))
    plot(hr50, lty=3, lwd=1.5, border="azure4", add=T,axes=F)
    plot(hr95, lty=1, lwd=1, border="cadetblue2", add=T, axes=F)
    plot(hr99, lty=4, lwd=1, border="darkturquoise", add=T, axes=F)
    plot(SUAQ_contour_sf_loc,lty=3, lwd=0.2, col=alpha("black", 1), add=T, axes=F)
    plot(SUAQ_station_sf_loc,pch = 21,cex=1.5, col=alpha("black", 0.7), add=T, axes=F)
    plot(SUAQ_station_sf_loc,pch = 16,cex=1, col=alpha("darkred", 0.7),lwd=0.3, bg="darkred", add=T, axes=F)
    plot(SUAQ_river_sf_loc,lty=1, lwd=0.3, col=alpha("cornflowerblue", 0.7), add=T, axes=F)
    plot(SUAQ_pathnetwork_sf_loc, lty=1, lwd=0.3, col=alpha("darkolivegreen", 0.7), add=T, axes=F)
    axis(1, at=xmin_xmax_round_steps,pos=ymin+150) # x axis
    axis(2, at=ymin_ymax_round_steps, pos=xmin-500)
    #text(xmin-500, (ymin+ymax)/2, "y [m]", adj=c(NA,-4), srt=90)
    title(paste(selected_females[[iterator]], ": KDE ", "(", methListTitle[[j]], ")", sep=""), line=-1.5)
    legend("topright", c("HR 50%", "HR 95%", "HR 100%","Trail","River"), col=c("coral1", "cadetblue2", "darkturquoise","darkred",alpha("cornflowerblue", 0.7)), lwd=c(2.5,2,2,0.3,4), lty=c(3,1,4,1,1), inset=c(legendoffsety,legendoffsety))
    dev.off()
    
    results_selectedmethod <- data.frame(bandwithmethod=c(methList[[j]],methList[[j]],methList[[j]]),
            hrpercentage=c("50%","95%","99%"),
            area=c(hr50_sf$area,hr95_sf$area,hr99_sf$area),
            n_gps=c(n_gps,n_gps,n_gps),
            n_follows=c(n_follows,n_follows,n_follows),
            geometry=c(hr50_sf$geometry,hr95_sf$geometry,hr99_sf$geometry))

    results_selectedfocal<- results_selectedmethod %>% mutate(focal=selected_females[[iterator]])
    
    results_focal <- rbind(results_focal,results_selectedfocal)
  }

  

  print(paste(selected_females[[iterator]], ": Calculation finished", sep=""))
  iterator <- iterator+1
}
results_focal <- results_focal %>% mutate(period=names(mt_list)[samplinginterval])
kde_results_perperyear <- kde_results_perperyear %>% rbind(results_focal)


}
st_write(kde_results_perperyear, dsn = paste(
  paste(
    "output/Homeranges/KDE/years/",
    format(Sys.Date(), "%Y%m%d"),"/",
    "kde_values_years",
    sep = ""
  ),
  "shp",
  sep = "."
))
system("say alle kernel distanzen berechnet für jedes Jahr")


```


```{r LOCOH - HR per-researchperiods and all - HR sizes,echo=FALSE, message=FALSE,comment=FALSE, warning=FALSE}
# createa directory for kde periods calculation (named by the current date)
dir.create(paste(
    "output/Homeranges/LOCOH/periods/",
    format(Sys.Date(), "%Y%m%d"),
    sep = ""
  ))
imdir <- paste("output/Homeranges/LOCOH/periods/",format(Sys.Date(), "%Y%m%d"), "/", sep="")

locoh_list <- data.frame() # results
for (samplinginterval in c(1:length(mt_list))){
  print(paste("LOCOH for period: ",samplinginterval))
  ##### Determine the smoothing parameters
  selected_females <- mt_list[[samplinginterval]] %>% group_by(focal) %>% summarise()
  selected_females <- as_vector(selected_females)
  
  iterator <- 1
  for (i in selected_females) { # do the following for every animal in the list
    print(paste("LOCOH for focal: ",i))
    n_follows <- mt_list[[samplinginterval]] %>% filter(focal%in%c(i)) %>%
        group_by(follow) %>% summarise() %>% nrow()

    xy_selected <- mt_list[[samplinginterval]] %>% filter(focal%in%c(i)) %>%
      dplyr::select(E,N,manualDatetime,infantname,followtype,Activity,SUAQ_followlog.Observer1,SUAQ_orangutans.dominancecat,SUAQ_orangutans.matriline,SUAQ_weather.rainfall_ml_evening,SUAQ_fai.fai,ageFromDOB)
    xy_selected <- xy_selected[order(xy_selected$manualDatetime , decreasing = FALSE ),] 
    n_gps <- xy_selected %>% nrow()

    xy_only <- xy_selected %>%
      dplyr::select(E,N) %>% mutate(x=as.double(E),y=as.double(N)) %>% as.data.frame() %>% dplyr::select(-E,-N) # dataframe was a tibble --> caused troubles in the locoh package

    df.lxy <- xyt.lxy(xy=xy_only, dt=xy_selected$manualDatetime,anv=xy_selected[,4:12], id=i, proj4string=CRS("+init=epsg:23847")) # create xy-object. Duplicates are autom. removed
    # plot(df.lxy)
    hist(df.lxy) #distribution of locations by date, step length and SI -> some gaps, several SI
    # lxy.plot.freq(df.lxy, deltat.by.date=T) #sampling frequency over time -> several SI
    # lxy.plot.freq(df.lxy, cp=T) #find bursts of points that need to be thinned out, 2 sections because of two main SI
    
    # find bursts
    df.lxy <- lxy.thin.bursts(df.lxy, thresh=0.98) ## adjust threshold
    df.lxy <- lxy.ptsh.add(df.lxy)# find appropriate time parameter s. with rule from manual. Depending on RQ --> f.e. researching daily movement we want high s because we want two points near each other not as nearest neighbour because its seperated by a day.
    
    # # find s    
    # lxy.plot.pt2ctr(df.lxy) # proposes a s-value around 0.4
    # lxy.plot.sfinder(df.lxy, delta.t=3600*c(12,24,36,48,96,192)) # proposes a s-value around 0.15 # see how the time gaps are distributed compared to s selection. How much of timegap should be included in nearest neighbour
    # lxy.plot.mtdr(df.lxy, k=10)
    # lxy.plot.tspan(df.lxy, k=10) 
    
    ########################
    svalue <- 0.01      ###### s-VALUE SELECTION
    kselected <- 12    ## kmax-SELECTION
    aval <- 7000
    ########################
    
    df.lxy <- lxy.nn.add(df.lxy, s=svalue, k=kselected)
    df.lhs_12k <- lxy.lhs(df.lxy, k=kselected, s=svalue)
    df.lhs_12k <- lhs.iso.add(df.lhs_12k, iso.levels = c(0.25, 0.5, 0.65, 0.75, 0.85, 0.95)) # creates isopleths for each k-hullset, sorted by density
    

    
    # a method
    df.lxy <- lxy.nn.add(df.lxy, s=svalue, a=auto.a(nnn=12, ptp=0.98))
    df.lxy <- lxy.nn.add(df.lxy, s=svalue, a=12000)
    lhs_amixed <- lxy.lhs(df.lxy, s=svalue, a=4:12*1000, iso.add=T)
    
    for (l in seq(1:length(kmax_vec))) {
      start_time <- Sys.time()
      kmax <- kmax_vec[[l]]
      df.lxy <- lxy.nn.add(df.lxy, s=0.02, k=kmax)
      
      
      # revisits
      df.lhs_12k_revisits <- lhs.visit.add(df.lhs_12k, ivg=3600*18)
      summary(df.lhs_12k_revisits)
      plot(df.lhs_12k_revisits, hpp=T, hpp.classify="nsv", ivg=3600*18, col.ramp="rainbow") # number of visits
      plot(df.lhs_12k_revisits, hpp=T, hpp.classify="mnlv", col.ramp="rainbow") # duration of visit
      hsp <- lhs.plot.scatter(df.lhs_12k_revisits, x="nsv", y="mnlv", col="spiral", bg="black")
      plot(df.lhs_12k_revisits, hpp=T, hsp=hsp, hpp.classify="hsp")
      
      # Directional movement
      df.lhs_12k_directional <- lhs.ellipses.add(df.lhs_12k)
      df.lhs_12k_directional <- lhs.iso.add(df.lhs_12k_directional, sort.metric="ecc")
      plot(df.lhs_12k_directional, iso=T, iso.sort.metric="ecc")
      #lhs.save(df.lhs, dir=paste("~/_MyData/Masterarbeit Movement Analysis/Resultate/thesis/calculations/LCH/", animal, sep="")
      # plot(df.lhs, iso=T, record=T, ufipt=F) #Show results of the different k-/a-/r-values [pg up / pg dn]]
      # lhs.plot.isoarea(df.lhs, legend=0)
      # lhs.plot.isoear(df.lhs, legend=0)
      plot(df.lhs_12k_directional, iso=T, k=12, allpts=T, cex.allpts=0.3, col.allpts="gray30", ufipt=F)
      
      
      
      
      
      
      
      if(TRUE){# only execute when enough data xy_selected_toolessdata
      UD <- BRB(traj, D=vv, Tmax=tmax, Lmin=lmin, hmin=hmin, b=T, same4all=T, grid=gridVal, extent=extVal, filtershort=T, type="UD")
      
      hr95 <- getverticeshr(UD, percent=95, standardize=TRUE,unin = c("m"),unout = c("km2"))
      hr50 <- getverticeshr(UD, percent=50, standardize=TRUE,unin = c("m"),unout = c("km2"))
      hr99 <- getverticeshr(UD, percent=99, standardize=TRUE,unin = c("m"),unout = c("km2"))
      hr95_sf <- st_as_sf(hr95)
      hr50_sf <- st_as_sf(hr50)
      hr99_sf <- st_as_sf(hr99)
      
      par(0,0,0,0)
      step <- 200
      
      ########## plot results ##########
      hminTxt <- gsub(".", "_", as.character(hminFactor[[l]]), fixed=T)
      xmin_xmax_round_steps<- c(step*(ceiling(xmin/step)):(round(xmax/step)))
      xmin_xmax_round_steps <- xmin_xmax_round_steps[2:(length(xmin_xmax_round_steps)-2)] #manual adjustment of tick breaks how many does it need
      ymin_ymax_round_steps<- c(step*(ceiling(ymin/step)):(round(ymax/step)))
      ymin_ymax_round_steps <- ymin_ymax_round_steps[2:(length(ymin_ymax_round_steps)-1)] #manual adjustment of tick breaks how many does it need    
      
  
      
      png(paste(imdir,i, "_BRB_UD_", hminTxt,"_",names(mt_list)[samplinginterval], ".png", sep=""), width=1800, height=1400, res=240, units="px")
      image(UD, xlab="x [m]",ylab="y [m]",xlim=c(xmin_xmax_round_steps[1],tail(xmin_xmax_round_steps,n=1)),ylim=c(ymin_ymax_round_steps[1],tail(ymin_ymax_round_steps,n=1))) 
      plot(hr50, lty=3, lwd=1.5, border="darkseagreen3", add=T,axes=F)
      plot(hr95, lty=1, lwd=1, border="cadetblue2", add=T, axes=F)
      plot(hr99, lty=4, lwd=1, border="darkturquoise", add=T, axes=F)
      plot(SUAQ_contour_sf_loc,lty=3, lwd=0.2, col=alpha("black", 1), add=T, axes=F)
      plot(SUAQ_station_sf_loc,pch = 21,cex=1.5, col=alpha("black", 0.7), add=T, axes=F)
      plot(SUAQ_station_sf_loc,pch = 16,cex=1, col=alpha("darkred", 0.7),lwd=0.3, bg="darkred", add=T, axes=F)
      plot(SUAQ_river_sf_loc,lty=1, lwd=0.3, col=alpha("cornflowerblue", 0.7), add=T, axes=F)
      plot(SUAQ_pathnetwork_sf_loc, lty=1, lwd=0.3, col=alpha("darkolivegreen", 0.7), add=T, axes=F)
      axis(1, at=xmin_xmax_round_steps,pos=ymin+axisshifty) # x axis
      axis(2, at=ymin_ymax_round_steps, pos=xmin+axisshiftx)
      title(paste(i, ": BRB (", hminFactor[[l]], "*hmin)", sep=""), line=-1.5)
      legend("topright", c("HR 50%", "HR 95%", "HR 100%","Trail","River"), col=c("coral1", "cadetblue2", "darkturquoise","darkred",alpha("cornflowerblue", 0.7)), lwd=c(2.5,2,2,0.3,4), lty=c(3,1,4,1,1), inset=c(legendoffsety,legendoffsety))
      dev.off()
      
      png(paste(imdir,i, "_BRB_VUD_", hminTxt,"_",names(mt_list)[samplinginterval], ".png", sep=""), width=1800, height=1400, res=240, units="px")
      image(getvolumeUD(UD), xlab="x [m]",ylab="y [m]",xlim=c(xmin_xmax_round_steps[1],tail(xmin_xmax_round_steps,n=1)),ylim=c(ymin_ymax_round_steps[1],tail(ymin_ymax_round_steps,n=1))) 
      plot(hr50, lty=3, lwd=1.5, border="darkseagreen3", add=T,axes=F)
      plot(hr95, lty=1, lwd=1, border="cadetblue2", add=T, axes=F)
      plot(hr99, lty=4, lwd=1, border="darkturquoise", add=T, axes=F)
      plot(SUAQ_contour_sf_loc,lty=3, lwd=0.2, col=alpha("black", 1), add=T, axes=F)
      plot(SUAQ_station_sf_loc,pch = 21,cex=1.5, col=alpha("black", 0.7), add=T, axes=F)
      plot(SUAQ_station_sf_loc,pch = 16,cex=1, col=alpha("darkred", 0.7),lwd=0.3, bg="darkred", add=T, axes=F)
      plot(SUAQ_river_sf_loc,lty=1, lwd=0.3, col=alpha("cornflowerblue", 0.7), add=T, axes=F)
      plot(SUAQ_pathnetwork_sf_loc, lty=1, lwd=0.3, col=alpha("darkolivegreen", 0.7), add=T, axes=F)
      axis(1, at=xmin_xmax_round_steps,pos=ymin+axisshifty) # x axis
      axis(2, at=ymin_ymax_round_steps, pos=xmin+axisshiftx)
      title(paste(i, ": BRB (", hminFactor[[l]], "*hmin)", sep=""), line=-1.5)
      legend("topright", c("HR 50%", "HR 95%", "HR 100%","Trail","River"), col=c("coral1", "cadetblue2", "darkturquoise","darkred",alpha("cornflowerblue", 0.7)), lwd=c(2.5,2,2,0.3,4), lty=c(3,1,4,1,1), inset=c(legendoffsety,legendoffsety))
      dev.off()}
      
      end_time <- Sys.time()
      duration <- end_time-start_time
      
      ########## export results ############
      if(xy_selected_toolessdata) {
        resultList_50 <-
          data.frame(
            focal = i,
            homerange = hr50$area,
            hrpercentage ="50%",
            n_gps = n_gps,
            n_follows = n_follows,
            Velocity_percentile99 = velocity,
            GPSuncertainty = relUn,
            hmin = hmin,
            tmax = tmax,
            lmin = lmin,
            tau = tau,
            hminfac = hminFactor[[l]],
            hminRef = hminRef,
            period = names(mt_list)[samplinginterval],
            processingtime = duration,
            geometry=hr50_sf$geometry
          )
        resultList_95 <-
          data.frame(
            focal = i,
            homerange = hr95$area,
            hrpercentage ="95%",
            n_gps = n_gps,
            n_follows = n_follows,
            Velocity_percentile99 = velocity,
            GPSuncertainty = relUn,
            hmin = hmin,
            tmax = tmax,
            lmin = lmin,
            tau = tau,
            hminfac = hminFactor[[l]],
            hminRef = hminRef,
            period = names(mt_list)[samplinginterval],
            processingtime = duration,
            geometry=hr95_sf$geometry
          )
        resultList_99 <-
          data.frame(
            focal = i,
            homerange = hr99$area,
            hrpercentage ="99%",
            n_gps = n_gps,
            n_follows = n_follows,
            Velocity_percentile99 = velocity,
            GPSuncertainty = relUn,
            hmin = hmin,
            tmax = tmax,
            lmin = lmin,
            tau = tau,
            hminfac = hminFactor[[l]],
            hminRef = hminRef,
            period = names(mt_list)[samplinginterval],
            processingtime = duration,
            geometry=hr99_sf$geometry
          )
      }
      if (!xy_selected_toolessdata) {
                resultList_50 <-
          data.frame(
            focal = i,
            homerange = NA,
            hrpercentage ="50%",
            n_gps = n_gps,
            n_follows = n_follows,
            Velocity_percentile99 = velocity,
            GPSuncertainty = relUn,
            hmin = hmin,
            tmax = tmax,
            lmin = lmin,
            tau = tau,
            hminfac = hminFactor[[l]],
            hminRef = hminRef,
            period = names(mt_list)[samplinginterval],
            processingtime = duration,
            geometry=NA
          )
        resultList_95 <-
          data.frame(
            focal = i,
            homerange = NA,
            hrpercentage ="95%",
            n_gps = n_gps,
            n_follows = n_follows,
            Velocity_percentile99 = velocity,
            GPSuncertainty = relUn,
            hmin = hmin,
            tmax = tmax,
            lmin = lmin,
            tau = tau,
            hminfac = hminFactor[[l]],
            hminRef = hminRef,
            period = names(mt_list)[samplinginterval],
            processingtime = duration,
            geometry=NA
          )
        resultList_99 <-
          data.frame(
            focal = i,
            homerange = NA,
            hrpercentage ="99%",
            n_gps = n_gps,
            n_follows = n_follows,
            Velocity_percentile99 = velocity,
            GPSuncertainty = relUn,
            hmin = hmin,
            tmax = tmax,
            lmin = lmin,
            tau = tau,
            hminfac = hminFactor[[l]],
            hminRef = hminRef,
            period = names(mt_list)[samplinginterval],
            processingtime = duration,
            geometry=NA
          )
      }
      locoh_list <- locoh_list %>% rbind(resultList_50,resultList_95,resultList_99)
      
      print(paste(hminTxt, ": Calculation finished", sep=""))
    }
  }
}

st_write(locoh_list, dsn = paste(
  paste(
    imdir,
    "locoh_values_allperiods",
    sep = ""
  ),
  "shp",
  sep = "."
))
system("say alle locoh verteilungen berechnet für die verschiedenen Untersuchungsperioden")

lhs.plot.isoarea(cissy.lhs.amixed)
lhs.plot.isoear(cissy.lhs.amixed)
toni.lhs.k15 <- lhs.visit.add(toni.lhs.k15, ivg=3600*12)

```

```{r BRB - HR per-researchperiods and all - HR sizes,echo=FALSE, message=FALSE,comment=FALSE, warning=FALSE}
# createa directory for kde periods calculation (named by the current date)
dir.create(paste(
    "output/Homeranges/BRB/periods/",
    format(Sys.Date(), "%Y%m%d"),
    sep = ""
  ))
imdir <- paste("output/Homeranges/BRB/periods/",format(Sys.Date(), "%Y%m%d"), "/", sep="")

#### retrieve sampling intervals
mainSI <- rep(30,length(selected_females))

brb_list <- data.frame() # results
for (samplinginterval in c(1:length(mt_list))){
  print(paste("brb for period: ",samplinginterval))
  ##### Determine the smoothing parameters
  selected_females <- mt_list[[samplinginterval]] %>% group_by(focal) %>% summarise()
  selected_females <- as_vector(selected_females)
  
  iterator <- 1
  for (i in selected_females) { # do the following for every animal in the list
    print(paste("brb for focal: ",i))
    n_follows <- mt_list[[samplinginterval]] %>% filter(focal%in%c(i)) %>%
        group_by(follow) %>% summarise() %>% nrow()

    xy_selected <- mt_list[[samplinginterval]] %>% filter(focal%in%c(i)) %>%
      dplyr::select(E,N,timelag_lead,manualDatetime)
    n_gps <- xy_selected %>% nrow()

    colnames(xy_selected) <- c("x","y","timelag_lead","timestamp") #adjust column names
    xy_selected <- xy_selected %>%  mutate(timelag_lead = round(timelag_lead,digits=0))
  
    # only select points where timegaps are between 20-40min --> To do pretty bad selection we would need a function which selects points automatically by subsampling if mean timegap is too high or by interpolating if too small. But how much does it really affect the result of HR --> because we mainly compare HR sizes.
    #xy_selected <- xy_selected %>% filter((timelag_lead/60)>20) #select which SI to remove (xy_selected$timelag_lead/60 < (mainSI[[iterator]]-10))
    #xy_selected <- xy_selected %>% filter((timelag_lead/60)<40)
    #xy_selected <- xy_selected[!(is.na(xy_selected$y)),]
    
    # check if enough gps points are still here otherwise make NA's
    xy_selected_toolessdata <- TRUE
    if(nrow(xy_selected)<30){xy_selected_toolessdata <- FALSE}
    
    # samplingI <- vector()
    # samplingI <- xy_selected$timelag_lead/60
    # samplingI <- samplingI[2:length(samplingI)] # First value of timelag_lead is NA
    # plot(table(samplingI), type="h", xlim=c(20,40),col=4, ylab="frequency", xlab="sampling interval [min]")
    
    xy_selected <- xy_selected[order(xy_selected$timestamp , decreasing = FALSE ),] 
    moveObj <- move(x=xy_selected$x, y=xy_selected$y, time=xy_selected$timestamp, proj=CRS( "+proj=utm +zone=47 +a=6378160 +b=6356774.50408554 +towgs84=-24,-15,5,0,0,0,0 +units=m +no_defs" ),animal=i)
    ##########################################################################################
    relUn <- 12 # relocation uncertainty [m]
    ##########################################################################################
    velocity <- unname(quantile(speed(moveObj), 0.99)) * 60 # unit: [m/min]
    hmin <- relUn + (0.5 * velocity * 30) # meters, smoothing
    iterator <- iterator+1
    
    
    
    traj <- as.ltraj(xy=xy_selected[,c("x", "y")], date=xy_selected$timestamp, id=i)
  
    ##########################################################################################
    tmax <- 70*60 # seconds, maximum time span for a segment
    lmin <- 12 # meters, minimal distance of a segment in order to count as movement
    tau <- 1*60 #seconds, approx. duration of one interpolated interval -> defines the number of intervals per step 
    extVal <- 15
    gridVal <- 2000
    hminRef <- hmin # computed through "BRB_leo_hmin computation.R"
    hminFactor <- c(0.6, 0.8, 1,1.2,1.4,  1.6, 1.8)
    ##########################################################################################
  
    vv <- BRB.D(traj, Tmax=tmax, Lmin=lmin) #estimate the diffusion coefficient
    for (l in seq(1:length(hminFactor))) {
      start_time <- Sys.time()
      hmin <- hminFactor[[l]]*hminRef
      if(xy_selected_toolessdata){# only execute when enough data
      UD <- BRB(traj, D=vv, Tmax=tmax, Lmin=lmin, hmin=hmin, b=T, same4all=T, grid=gridVal, extent=extVal, filtershort=T, type="UD")
      
      hr95 <- getverticeshr(UD, percent=95, standardize=TRUE,unin = c("m"),unout = c("km2"))
      hr50 <- getverticeshr(UD, percent=50, standardize=TRUE,unin = c("m"),unout = c("km2"))
      hr99 <- getverticeshr(UD, percent=99, standardize=TRUE,unin = c("m"),unout = c("km2"))
      hr95_sf <- st_as_sf(hr95)
      hr50_sf <- st_as_sf(hr50)
      hr99_sf <- st_as_sf(hr99)
      
      par(0,0,0,0)
      step <- 200
      
      ########## plot results ##########
      hminTxt <- gsub(".", "_", as.character(hminFactor[[l]]), fixed=T)
      xmin_xmax_round_steps<- c(step*(ceiling(xmin/step)):(round(xmax/step)))
      xmin_xmax_round_steps <- xmin_xmax_round_steps[2:(length(xmin_xmax_round_steps)-2)] #manual adjustment of tick breaks how many does it need
      ymin_ymax_round_steps<- c(step*(ceiling(ymin/step)):(round(ymax/step)))
      ymin_ymax_round_steps <- ymin_ymax_round_steps[2:(length(ymin_ymax_round_steps)-1)] #manual adjustment of tick breaks how many does it need    
      
  
      
      png(paste(imdir,i, "_BRB_UD_", hminTxt,"_",names(mt_list)[samplinginterval], ".png", sep=""), width=1800, height=1400, res=240, units="px")
      image(UD, xlab="x [m]",ylab="y [m]",xlim=c(xmin_xmax_round_steps[1],tail(xmin_xmax_round_steps,n=1)),ylim=c(ymin_ymax_round_steps[1],tail(ymin_ymax_round_steps,n=1))) 
      plot(hr50, lty=3, lwd=1.5, border="darkseagreen3", add=T,axes=F)
      plot(hr95, lty=1, lwd=1, border="cadetblue2", add=T, axes=F)
      plot(hr99, lty=4, lwd=1, border="darkturquoise", add=T, axes=F)
      plot(SUAQ_contour_sf_loc,lty=3, lwd=0.2, col=alpha("black", 1), add=T, axes=F)
      plot(SUAQ_station_sf_loc,pch = 21,cex=1.5, col=alpha("black", 0.7), add=T, axes=F)
      plot(SUAQ_station_sf_loc,pch = 16,cex=1, col=alpha("darkred", 0.7),lwd=0.3, bg="darkred", add=T, axes=F)
      plot(SUAQ_river_sf_loc,lty=1, lwd=0.3, col=alpha("cornflowerblue", 0.7), add=T, axes=F)
      plot(SUAQ_pathnetwork_sf_loc, lty=1, lwd=0.3, col=alpha("darkolivegreen", 0.7), add=T, axes=F)
      axis(1, at=xmin_xmax_round_steps,pos=ymin+axisshifty) # x axis
      axis(2, at=ymin_ymax_round_steps, pos=xmin+axisshiftx)
      title(paste(i, ": BRB (", hminFactor[[l]], "*hmin)", sep=""), line=-1.5)
      legend("topright", c("HR 50%", "HR 95%", "HR 100%","Trail","River"), col=c("coral1", "cadetblue2", "darkturquoise","darkred",alpha("cornflowerblue", 0.7)), lwd=c(2.5,2,2,0.3,4), lty=c(3,1,4,1,1), inset=c(legendoffsety,legendoffsety))
      dev.off()
      
      png(paste(imdir,i, "_BRB_VUD_", hminTxt,"_",names(mt_list)[samplinginterval], ".png", sep=""), width=1800, height=1400, res=240, units="px")
      image(getvolumeUD(UD), xlab="x [m]",ylab="y [m]",xlim=c(xmin_xmax_round_steps[1],tail(xmin_xmax_round_steps,n=1)),ylim=c(ymin_ymax_round_steps[1],tail(ymin_ymax_round_steps,n=1))) 
      plot(hr50, lty=3, lwd=1.5, border="darkseagreen3", add=T,axes=F)
      plot(hr95, lty=1, lwd=1, border="cadetblue2", add=T, axes=F)
      plot(hr99, lty=4, lwd=1, border="darkturquoise", add=T, axes=F)
      plot(SUAQ_contour_sf_loc,lty=3, lwd=0.2, col=alpha("black", 1), add=T, axes=F)
      plot(SUAQ_station_sf_loc,pch = 21,cex=1.5, col=alpha("black", 0.7), add=T, axes=F)
      plot(SUAQ_station_sf_loc,pch = 16,cex=1, col=alpha("darkred", 0.7),lwd=0.3, bg="darkred", add=T, axes=F)
      plot(SUAQ_river_sf_loc,lty=1, lwd=0.3, col=alpha("cornflowerblue", 0.7), add=T, axes=F)
      plot(SUAQ_pathnetwork_sf_loc, lty=1, lwd=0.3, col=alpha("darkolivegreen", 0.7), add=T, axes=F)
      axis(1, at=xmin_xmax_round_steps,pos=ymin+axisshifty) # x axis
      axis(2, at=ymin_ymax_round_steps, pos=xmin+axisshiftx)
      title(paste(i, ": BRB (", hminFactor[[l]], "*hmin)", sep=""), line=-1.5)
      legend("topright", c("HR 50%", "HR 95%", "HR 100%","Trail","River"), col=c("coral1", "cadetblue2", "darkturquoise","darkred",alpha("cornflowerblue", 0.7)), lwd=c(2.5,2,2,0.3,4), lty=c(3,1,4,1,1), inset=c(legendoffsety,legendoffsety))
      dev.off()}
      
      end_time <- Sys.time()
      duration <- end_time-start_time
      
      ########## export results ############
      if(xy_selected_toolessdata) {
        resultList_50 <-
          data.frame(
            focal = i,
            homerange = hr50$area,
            hrpercentage ="50%",
            n_gps = n_gps,
            n_follows = n_follows,
            Velocity_percentile99 = velocity,
            GPSuncertainty = relUn,
            hmin = hmin,
            tmax = tmax,
            lmin = lmin,
            tau = tau,
            hminfac = hminFactor[[l]],
            hminRef = hminRef,
            period = names(mt_list)[samplinginterval],
            processingtime = duration,
            geometry=hr50_sf$geometry
          )
        resultList_95 <-
          data.frame(
            focal = i,
            homerange = hr95$area,
            hrpercentage ="95%",
            n_gps = n_gps,
            n_follows = n_follows,
            Velocity_percentile99 = velocity,
            GPSuncertainty = relUn,
            hmin = hmin,
            tmax = tmax,
            lmin = lmin,
            tau = tau,
            hminfac = hminFactor[[l]],
            hminRef = hminRef,
            period = names(mt_list)[samplinginterval],
            processingtime = duration,
            geometry=hr95_sf$geometry
          )
        resultList_99 <-
          data.frame(
            focal = i,
            homerange = hr99$area,
            hrpercentage ="99%",
            n_gps = n_gps,
            n_follows = n_follows,
            Velocity_percentile99 = velocity,
            GPSuncertainty = relUn,
            hmin = hmin,
            tmax = tmax,
            lmin = lmin,
            tau = tau,
            hminfac = hminFactor[[l]],
            hminRef = hminRef,
            period = names(mt_list)[samplinginterval],
            processingtime = duration,
            geometry=hr99_sf$geometry
          )
      }
      if (!xy_selected_toolessdata) {
                resultList_50 <-
          data.frame(
            focal = i,
            homerange = NA,
            hrpercentage ="50%",
            n_gps = n_gps,
            n_follows = n_follows,
            Velocity_percentile99 = velocity,
            GPSuncertainty = relUn,
            hmin = hmin,
            tmax = tmax,
            lmin = lmin,
            tau = tau,
            hminfac = hminFactor[[l]],
            hminRef = hminRef,
            period = names(mt_list)[samplinginterval],
            processingtime = duration,
            geometry=NA
          )
        resultList_95 <-
          data.frame(
            focal = i,
            homerange = NA,
            hrpercentage ="95%",
            n_gps = n_gps,
            n_follows = n_follows,
            Velocity_percentile99 = velocity,
            GPSuncertainty = relUn,
            hmin = hmin,
            tmax = tmax,
            lmin = lmin,
            tau = tau,
            hminfac = hminFactor[[l]],
            hminRef = hminRef,
            period = names(mt_list)[samplinginterval],
            processingtime = duration,
            geometry=NA
          )
        resultList_99 <-
          data.frame(
            focal = i,
            homerange = NA,
            hrpercentage ="99%",
            n_gps = n_gps,
            n_follows = n_follows,
            Velocity_percentile99 = velocity,
            GPSuncertainty = relUn,
            hmin = hmin,
            tmax = tmax,
            lmin = lmin,
            tau = tau,
            hminfac = hminFactor[[l]],
            hminRef = hminRef,
            period = names(mt_list)[samplinginterval],
            processingtime = duration,
            geometry=NA
          )
      }
      brb_list <- brb_list %>% rbind(resultList_50,resultList_95,resultList_99)
      
      print(paste(hminTxt, ": Calculation finished", sep=""))
    }
  }
}

st_write(brb_list, dsn = paste(
  paste(
    imdir,
    "brb_values_allperiods",
    sep = ""
  ),
  "shp",
  sep = "."
))
system("say alle kernel distanzen berechnet für die verschiedenen Untersuchungsperioden")


```

```{r BRB - HR per-year and all - HR sizes,echo=FALSE, message=FALSE,comment=FALSE, warning=FALSE}
# createa directory for kde periods calculation (named by the current date)
dir.create(paste(
    "output/Homeranges/BRB/periods/",
    format(Sys.Date(), "%Y%m%d"),
    sep = ""
  ))
imdir <- paste("output/Homeranges/BRB/periods/",format(Sys.Date(), "%Y%m%d"), "/", sep="")

#### retrieve sampling intervals
mainSI <- rep(30,length(selected_females))

brb_list <- data.frame() # results
for (samplinginterval in c(1:length(mt_list))){
  print(paste("brb for period: ",samplinginterval))
  ##### Determine the smoothing parameters
  selected_females <- mt_list[[samplinginterval]] %>% group_by(focal) %>% summarise()
  selected_females <- as_vector(selected_females)
  
  iterator <- 1
  for (i in selected_females) { # do the following for every animal in the list
    print(paste("brb for focal: ",i))
    xy_selected <- mt_list[[samplinginterval]] %>% filter(focal%in%c(i)) %>% dplyr::select(E,N,timelag_lead,manualDatetime)
    
    colnames(xy_selected) <- c("x","y","timelag_lead","timestamp") #adjust column names
    xy_selected <- xy_selected %>%  mutate(timelag_lead = round(timelag_lead,digits=0))
  
    # only select points where timegaps are between 20-40min --> To do pretty bad selection we would need a function which selects points automatically by subsampling if mean timegap is too high or by interpolating if too small. But how much does it really affect the result of HR --> because we mainly compare HR sizes.
    #xy_selected <- xy_selected %>% filter((timelag_lead/60)>20) #select which SI to remove (xy_selected$timelag_lead/60 < (mainSI[[iterator]]-10))
    #xy_selected <- xy_selected %>% filter((timelag_lead/60)<40)
    #xy_selected <- xy_selected[!(is.na(xy_selected$y)),]
    
    # check if enough gps points are still here otherwise make NA's
    xy_selected_toolessdata <- TRUE
    if(nrow(xy_selected)<30){xy_selected_toolessdata <- FALSE}
    
    # samplingI <- vector()
    # samplingI <- xy_selected$timelag_lead/60
    # samplingI <- samplingI[2:length(samplingI)] # First value of timelag_lead is NA
    # plot(table(samplingI), type="h", xlim=c(20,40),col=4, ylab="frequency", xlab="sampling interval [min]")
    
    xy_selected <- xy_selected[order(xy_selected$timestamp , decreasing = FALSE ),] 
    moveObj <- move(x=xy_selected$x, y=xy_selected$y, time=xy_selected$timestamp, proj=CRS( "+proj=utm +zone=47 +a=6378160 +b=6356774.50408554 +towgs84=-24,-15,5,0,0,0,0 +units=m +no_defs" ),animal=i)
    ##########################################################################################
    relUn <- 12 # relocation uncertainty [m]
    ##########################################################################################
    velocity <- unname(quantile(speed(moveObj), 0.99)) * 60 # unit: [m/min]
    hmin <- relUn + (0.5 * velocity * 30) # meters, smoothing
    iterator <- iterator+1
    
    
    
    traj <- as.ltraj(xy=xy_selected[,c("x", "y")], date=xy_selected$timestamp, id=i)
  
    ##########################################################################################
    tmax <- 70*60 # seconds, maximum time span for a segment
    lmin <- 12 # meters, minimal distance of a segment in order to count as movement
    tau <- 1*60 #seconds, approx. duration of one interpolated interval -> defines the number of intervals per step 
    extVal <- 15
    gridVal <- 2000
    hminRef <- hmin # computed through "BRB_leo_hmin computation.R"
    hminFactor <- c(0.6, 0.8, 1,1.2,1.4,  1.6, 1.8)
    ##########################################################################################
  
    vv <- BRB.D(traj, Tmax=tmax, Lmin=lmin) #estimate the diffusion coefficient
    for (l in seq(1:length(hminFactor))) {
      start_time <- Sys.time()
      hmin <- hminFactor[[l]]*hminRef
      if(xy_selected_toolessdata){# only execute when enough data
      UD <- BRB(traj, D=vv, Tmax=tmax, Lmin=lmin, hmin=hmin, b=T, same4all=T, grid=gridVal, extent=extVal, filtershort=T, type="UD")
      
      hr95 <- getverticeshr(UD, percent=95, standardize=TRUE,unin = c("m"),unout = c("km2"))
      hr50 <- getverticeshr(UD, percent=50, standardize=TRUE,unin = c("m"),unout = c("km2"))
      hr99 <- getverticeshr(UD, percent=99, standardize=TRUE,unin = c("m"),unout = c("km2"))
      
      par(0,0,0,0)
      step <- 200
      
      ########## plot results ##########
      hminTxt <- gsub(".", "_", as.character(hminFactor[[l]]), fixed=T)
      xmin_xmax_round_steps<- c(step*(ceiling(xmin/step)):(round(xmax/step)))
      xmin_xmax_round_steps <- xmin_xmax_round_steps[2:(length(xmin_xmax_round_steps)-2)] #manual adjustment of tick breaks how many does it need
      ymin_ymax_round_steps<- c(step*(ceiling(ymin/step)):(round(ymax/step)))
      ymin_ymax_round_steps <- ymin_ymax_round_steps[2:(length(ymin_ymax_round_steps)-1)] #manual adjustment of tick breaks how many does it need    
      
  
      
      png(paste(imdir,i, "_BRB_UD_", hminTxt,"_",names(mt_list)[samplinginterval], ".png", sep=""), width=1800, height=1400, res=240, units="px")
      image(UD, xlab="x [m]",ylab="y [m]",xlim=c(xmin_xmax_round_steps[1],tail(xmin_xmax_round_steps,n=1)),ylim=c(ymin_ymax_round_steps[1],tail(ymin_ymax_round_steps,n=1))) 
      plot(hr50, lty=3, lwd=1.5, border="darkseagreen3", add=T,axes=F)
      plot(hr95, lty=1, lwd=1, border="cadetblue2", add=T, axes=F)
      plot(hr99, lty=4, lwd=1, border="darkturquoise", add=T, axes=F)
      plot(SUAQ_contour_sf_loc,lty=3, lwd=0.2, col=alpha("black", 1), add=T, axes=F)
      plot(SUAQ_station_sf_loc,pch = 21,cex=1.5, col=alpha("black", 0.7), add=T, axes=F)
      plot(SUAQ_station_sf_loc,pch = 16,cex=1, col=alpha("darkred", 0.7),lwd=0.3, bg="darkred", add=T, axes=F)
      plot(SUAQ_river_sf_loc,lty=1, lwd=0.3, col=alpha("cornflowerblue", 0.7), add=T, axes=F)
      plot(SUAQ_pathnetwork_sf_loc, lty=1, lwd=0.3, col=alpha("darkolivegreen", 0.7), add=T, axes=F)
      axis(1, at=xmin_xmax_round_steps,pos=ymin+axisshifty) # x axis
      axis(2, at=ymin_ymax_round_steps, pos=xmin+axisshiftx)
      title(paste(i, ": BRB (", hminFactor[[l]], "*hmin)", sep=""), line=-1.5)
      legend("topright", c("HR 50%", "HR 95%", "HR 100%","Trail","River"), col=c("coral1", "cadetblue2", "darkturquoise","darkred",alpha("cornflowerblue", 0.7)), lwd=c(2.5,2,2,0.3,4), lty=c(3,1,4,1,1), inset=c(legendoffsety,legendoffsety))
      dev.off()
      
      png(paste(imdir,i, "_BRB_VUD_", hminTxt,"_",names(mt_list)[samplinginterval], ".png", sep=""), width=1800, height=1400, res=240, units="px")
      image(getvolumeUD(UD), xlab="x [m]",ylab="y [m]",xlim=c(xmin_xmax_round_steps[1],tail(xmin_xmax_round_steps,n=1)),ylim=c(ymin_ymax_round_steps[1],tail(ymin_ymax_round_steps,n=1))) 
      plot(hr50, lty=3, lwd=1.5, border="darkseagreen3", add=T,axes=F)
      plot(hr95, lty=1, lwd=1, border="cadetblue2", add=T, axes=F)
      plot(hr99, lty=4, lwd=1, border="darkturquoise", add=T, axes=F)
      plot(SUAQ_contour_sf_loc,lty=3, lwd=0.2, col=alpha("black", 1), add=T, axes=F)
      plot(SUAQ_station_sf_loc,pch = 21,cex=1.5, col=alpha("black", 0.7), add=T, axes=F)
      plot(SUAQ_station_sf_loc,pch = 16,cex=1, col=alpha("darkred", 0.7),lwd=0.3, bg="darkred", add=T, axes=F)
      plot(SUAQ_river_sf_loc,lty=1, lwd=0.3, col=alpha("cornflowerblue", 0.7), add=T, axes=F)
      plot(SUAQ_pathnetwork_sf_loc, lty=1, lwd=0.3, col=alpha("darkolivegreen", 0.7), add=T, axes=F)
      axis(1, at=xmin_xmax_round_steps,pos=ymin+axisshifty) # x axis
      axis(2, at=ymin_ymax_round_steps, pos=xmin+axisshiftx)
      title(paste(i, ": BRB (", hminFactor[[l]], "*hmin)", sep=""), line=-1.5)
      legend("topright", c("HR 50%", "HR 95%", "HR 100%","Trail","River"), col=c("coral1", "cadetblue2", "darkturquoise","darkred",alpha("cornflowerblue", 0.7)), lwd=c(2.5,2,2,0.3,4), lty=c(3,1,4,1,1), inset=c(legendoffsety,legendoffsety))
      dev.off()}
      
      end_time <- Sys.time()
      duration <- end_time-start_time
      
      ########## export results ############
      if(xy_selected_toolessdata) {
        resultList_50 <-
          data.frame(
            focal = i,
            hr50 = hr50$area,
            n_gps = n_gps,
            n_follows = n_follows,
            Velocity_percentile99 = velocity,
            GPSuncertainty = relUn,
            hmin = hmin,
            tmax = tmax,
            lmin = lmin,
            tau = tau,
            hminfac = hminFactor[[l]],
            hminRef = hminRef,
            period = names(mt_list)[samplinginterval],
            processingtime = duration,
            geometry=hr50_sf$geometry
          )
        resultList_95 <-
          data.frame(
            focal = i,
            hr95 = hr95$area,
            n_gps = n_gps,
            n_follows = n_follows,
            Velocity_percentile99 = velocity,
            GPSuncertainty = relUn,
            hmin = hmin,
            tmax = tmax,
            lmin = lmin,
            tau = tau,
            hminfac = hminFactor[[l]],
            hminRef = hminRef,
            period = names(mt_list)[samplinginterval],
            processingtime = duration,
            geometry=hr95_sf$geometry
          )
        resultList_99 <-
          data.frame(
            focal = i,
            hr99 = hr99$area,
            n_gps = n_gps,
            n_follows = n_follows,
            Velocity_percentile99 = velocity,
            GPSuncertainty = relUn,
            hmin = hmin,
            tmax = tmax,
            lmin = lmin,
            tau = tau,
            hminfac = hminFactor[[l]],
            hminRef = hminRef,
            period = names(mt_list)[samplinginterval],
            processingtime = duration,
            geometry=hr99_sf$geometry
          )
      }
      if (!xy_selected_toolessdata) {
                resultList_50 <-
          data.frame(
            focal = i,
            hr50 = NA,
            n_gps = n_gps,
            n_follows = n_follows,
            Velocity_percentile99 = velocity,
            GPSuncertainty = relUn,
            hmin = hmin,
            tmax = tmax,
            lmin = lmin,
            tau = tau,
            hminfac = hminFactor[[l]],
            hminRef = hminRef,
            period = names(mt_list)[samplinginterval],
            processingtime = duration,
            geometry=NA
          )
        resultList_95 <-
          data.frame(
            focal = i,
            hr95 = NA,
            n_gps = n_gps,
            n_follows = n_follows,
            Velocity_percentile99 = velocity,
            GPSuncertainty = relUn,
            hmin = hmin,
            tmax = tmax,
            lmin = lmin,
            tau = tau,
            hminfac = hminFactor[[l]],
            hminRef = hminRef,
            period = names(mt_list)[samplinginterval],
            processingtime = duration,
            geometry=NA
          )
        resultList_99 <-
          data.frame(
            focal = i,
            hr99 = NA,
            n_gps = n_gps,
            n_follows = n_follows,
            Velocity_percentile99 = velocity,
            GPSuncertainty = relUn,
            hmin = hmin,
            tmax = tmax,
            lmin = lmin,
            tau = tau,
            hminfac = hminFactor[[l]],
            hminRef = hminRef,
            period = names(mt_list)[samplinginterval],
            processingtime = duration,
            geometry=NA
          )
      }
      brb_list <- brb_list %>% rbind(resultList_50,resultList_95,resultList_99)
      
      print(paste(hminTxt, ": Calculation finished", sep=""))
    }
  }
}

st_write(brb_list, dsn = paste(
  paste(
    imdir,
    "brb_values_years",
    sep = ""
  ),
  "shp",
  sep = "."
))
system("say alle kernel distanzen berechnet für jedes Jahr")


```

```{r dBBMM - HR sizes,echo=FALSE, message=FALSE,comment=FALSE, warning=FALSE}

```

```{r Homerange - VISUALS - HR sizes,echo=FALSE, message=FALSE,comment=FALSE, warning=FALSE}
#### Analyze ??: distribution of weather?
plot_anypoints <- SUAQ_waypoints_11all20_loc[order(SUAQ_waypoints_11all20_loc$manualDatetime , decreasing = FALSE ),] %>%
  filter(PtType=="nightnest") %>% 
  filter(SUAQ_weather.temperature_min_evening>0) %>% 
  group_by(follow) %>%
  ggplot()+
  geom_point(aes(E,N,color=log10(SUAQ_weather.temperature_min_evening)),size=2.5)+
  #geom_path(aes(E,N), alpha = 0.7,size=0.5)+
  geom_sf(data = SUAQ_pathnetwork_sf_loc,
                                               aes(colour = "black", alpha = 1),
                                               fill = NA,colour = "black")
  
ggplotly(plot_anypoints)

#### Analyze edges: Missing Homeranges?
SUAQ_waypoints_11all20_loc_lost <- SUAQ_waypoints_11all20_loc %>% filter(PtType%in%c("lost"))
SUAQ_waypoints_11all20_loc_lost

plot_lostpoints<-SUAQ_waypoints_11all20_loc_lost[order(SUAQ_waypoints_11all20_loc_lost$manualDatetime , decreasing = FALSE ),] %>%
  group_by(follow) %>%
  ggplot()+
  geom_point(data=SUAQ_waypoints_11all20_loc[order(SUAQ_waypoints_11all20_loc$manualDatetime , decreasing = FALSE ),], aes(E,N),size=0.2,fill="azure4",color="azure4",alpha=0.3)+
  geom_point(aes(E,N,color=focal),size=0.8)+
  geom_text(aes(E,N+40,label=focal,color=focal),size=3.5)+
  #geom_path(aes(E,N), alpha = 0.7,size=0.5)+
  geom_sf(data = SUAQ_pathnetwork_sf_loc,
                                               aes(colour = "black", alpha = 1),
                                               fill = NA,colour = "black")
  
ggplotly(plot_lostpoints)

#### Analyze weather: distribution of weather?
plot_weatherpoints<-SUAQ_waypoints_11all20_loc[order(SUAQ_waypoints_11all20_loc$manualDatetime , decreasing = FALSE ),] %>%
  filter(SUAQ_weather.rainfall_ml_evening!=0) %>% 
  #filter(PtType=="mornnest") %>% 
  group_by(follow) %>%
  ggplot()+
  geom_point(aes(E,N,color=log10(SUAQ_weather.rainfall_ml_evening)),size=1)+
  #geom_path(aes(E,N), alpha = 0.7,size=0.5)+
  geom_sf(data = SUAQ_pathnetwork_sf_loc,
                                               aes(colour = "black", alpha = 1),
                                               fill = NA,colour = "black")
  
ggplotly(plot_weatherpoints)

#### BRB: Find most recent folder
mostrecent <- list.dirs(path = "output/Homeranges/KDE/periods/", full.names = FALSE, recursive = FALSE)
mostrecent <- as.data.frame(mostrecent)
colnames(mostrecent) <- c("date")
mostrecent <- mostrecent %>% filter(date!="_archive") %>%  arrange(desc(date)) %>% top_n(1,date)
imdir <-paste("output/Homeranges/KDE/periods/",mostrecent$date[1], "/", sep="")
kde_values_allperiods <- read_csv(paste0(imdir,"kde_values_allperiods.csv"))

#### BRB: Find most recent folder
mostrecent <- list.dirs(path = "output/Homeranges/BRB/periods/", full.names = FALSE, recursive = FALSE)
mostrecent <- as.data.frame(mostrecent)
colnames(mostrecent) <- c("date")
mostrecent <- mostrecent %>% filter(date!="_archive") %>%  arrange(desc(date)) %>% top_n(1,date)
imdir <-paste("output/Homeranges/BRB/periods/",mostrecent$date[1], "/", sep="")

#### Load homerange results
brb_list <- read_csv(paste0(imdir,"brb_values_allperiods.csv"))

test<- SUAQ_rangepoints_11all20_loc %>% filter(focal%in%c("friska")) %>% filter(year(manualDate)<2012)
year(SUAQ_waypoints_11all20_loc$manualDate[1])

brb_selected_periods<- brb_list %>% 
  #filter(focal %in%c("ellie","lisa","friska","cissy"))%>% 
  mutate(period=fct_relevel(period, 
            "before 2012" ,"2012 until 2016","2016 until August 2018","Since August 2018","total research period"))
  #filter(hminfac==1)

brb_list_selected_err<-  brb_selected_periods %>% 
  mutate(hminfac=as.numeric(hminfac)) %>%  
  filter(hminfac %in% c(0.8,1.2))  %>% 
  spread(hminfac,hr95) %>%
  group_by(focal,nGPS,period) %>%
  summarise_each(funs(first(.[!is.na(.)]))) %>% 
  rename(hminfac_0_8=`0.8`,hminfac_1_2=`1.2`)



png(file=paste(
  paste(
    "/Users/stefgr/Dropbox/Apps/Overleaf/Msc_Thesis/figures/",
    format(Sys.Date(), "%Y%m%d"),"_",
    "brb_selected_periods",
    sep = ""
  ),
  "png",
  sep = "."
),width=900, height=700, res=120, units="px") # or other device
brb_selected_periods %>% filter(hminfac==1) %>% ggplot() + 
  geom_errorbar(data=brb_list_selected_err,aes(x=period,ymin=hminfac_0_8, ymax=hminfac_1_2,color=focal),width=0.2)+
  geom_point(aes(period,hr95,group=interaction(focal),color=focal),size=3)+
  geom_line(aes(period,hr95,group=interaction(focal),color=focal),size=0.5)+
  scale_color_brewer(palette="Set1") +
  theme_minimal()+
  geom_text(aes(x=period,y=hr95,label=nGPS),check_overlap = TRUE,hjust=1.5)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  theme(axis.title.x=element_blank())+
  labs(y=expression("Homerange 95% [km"^2*"]"))
dev.off()

```



Homerange Overlap:
